package tnt.blockychef.common.food;

import com.google.common.base.Supplier;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.food.Foods;

import java.util.IdentityHashMap;
import java.util.Map;

public final class FoodList {

    public static final Map<FoodProperties, FoodProperties> FOOD_OVERRIDES = new IdentityHashMap<>();

    private static final Supplier<MobEffectInstance> HUNGER = () -> new MobEffectInstance(MobEffects.HUNGER, 600, 7);
    private static final float PROBABILITY = 0.20F;


    // Vanilla overrides
    public static final FoodProperties COOKED_BEEF = food(2, 2).build();
    public static final FoodProperties COOKED_PORKCHOP = food(2, 2).build();
    public static final FoodProperties COOKED_MUTTON = food(2, 2).build();
    public static final FoodProperties COOKED_CHICKEN = food(2, 2).build();
    public static final FoodProperties COOKED_RABBIT = food(2, 2).build();
    public static final FoodProperties COOKED_COD = food(2, 2).build();
    public static final FoodProperties COOKED_SALMON = food(2, 2).build();
    public static final FoodProperties PUMPKIN_PIE = food(2, 2).build();
    public static final FoodProperties MUSHROOM_STEW = food(2, 1).build();
    public static final FoodProperties BEETROOT_SOUP = food(2, 2).build();
    public static final FoodProperties RABBIT_STEW = food(3, 2).build();
    public static final FoodProperties SUSPICIOUS_STEW = food(2, 2).build();
    public static final FoodProperties BREAD = food(3, 2).build();
    public static final FoodProperties HONEY_BOTTLE = food(2, 2).build();
    public static final FoodProperties APPLE = food(1, 1).build();
    public static final FoodProperties BEEF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PORKCHOP = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHICKEN = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MUTTON = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RABBIT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SALMON = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COD = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TROPICAL_FISH = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SWEET_BERRIES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GLOW_BERRIES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHORUS_FRUIT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties POTATO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEETROOT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties POISONOUS_POTATO = food(1, 1).effect(HUNGER, 0.5F).build();
    public static final FoodProperties ROTTEN_FLESH = food(2, 1).effect(HUNGER, 0.75F).build();
    public static final FoodProperties SPIDER_EYE = food(1, 1).effect(HUNGER, 0.95F).build();
    public static final FoodProperties GOLDEN_APPLE = food(2, 2).build();
    public static final FoodProperties DRIED_KELP = food(1, 1).build();
    public static final FoodProperties BAKED_POTATO = food(2, 2).build();
    public static final FoodProperties ENCHANTED_GOLDEN_APPLE = food(2, 2).build();
    public static final FoodProperties GOLDEN_CARROT = food(2, 2).build();
    public static final FoodProperties COOKIE = food(1, 1).build();
    public static final FoodProperties MELON_SLICE = food(1, 1).build();
    public static final FoodProperties CARROT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    // Blockychef foods
    public static final FoodProperties TOMATO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CUCUMBER = food(1, 1).alwaysEat().effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ALMOND = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BELL_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BLACK_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BLUEBERRY = food(1, 1).alwaysEat().build();
    public static final FoodProperties CHILLI_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BROCCOLI = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CABBAGE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CORN_COB = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GARLIC = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LEEK = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LETTUCE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ONION = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PARSLEY = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RASPBERRY = food(1, 1).alwaysEat().build();
    public static final FoodProperties SPRING_ONION = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties STRAWBERRY = food(1, 1).alwaysEat().build();
    public static final FoodProperties TURMERIC = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PINEAPPLE = food(1, 1).alwaysEat().build();
    public static final FoodProperties PORTOBELLO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEANS_POD = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEANUT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEA_POD = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SOYBEANS_POD = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BASIL = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GINGER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TEA_LEAF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GRAPES = food(1, 1).alwaysEat().build();
    public static final FoodProperties RICE_CROP = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties OAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MUSTARD_PODS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COFFEE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties EGGPLANT = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SPINACH_LEAF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties AVOCADO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BANANA = food(1, 1).build();
    public static final FoodProperties BLACK_OLIVES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHERRY = food(1, 1).alwaysEat().build();
    public static final FoodProperties GREEN_OLIVES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HAZELNUT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LEMON = food(1, 1).alwaysEat().effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LIME = food(1, 1).alwaysEat().effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ORANGE = food(1, 1).alwaysEat().build();
    public static final FoodProperties PEACH = food(1, 1).alwaysEat().build();
    public static final FoodProperties PEAR = food(1, 1).alwaysEat().build();
    public static final FoodProperties PLUM = food(1, 1).alwaysEat().build();
    public static final FoodProperties VANILLA_PODS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties WALNUT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHRIMP = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SHRIMP = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties FRIED_SHRIMP = food(2, 1).build();
    public static final FoodProperties APPLE_HALF = food(1, 1).build();
    public static final FoodProperties APPLE_MARMALADE = food(3, 2).build();
    public static final FoodProperties APPLE_SLICE = food(1, 1).build();
    public static final FoodProperties AVOCADO_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BANANA_SLICE = food(1, 1).build();
    public static final FoodProperties BBQ_SAUCE = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEANS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEEF_BURGER_PATTY = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEEF_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEETROOT_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BELL_PEPPER_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BLACK_OLIVE_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BLUEBERRY_MARMALADE = food(3, 2).build();
    public static final FoodProperties BOILED_RICE = food(2, 2).build();
    public static final FoodProperties BREAD_SLICE = food(1, 1).build();
    public static final FoodProperties BROCCOLI_CUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CABBAGE_LEAF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CARROT_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHERRY_MARMALADE = food(3, 2).build();
    public static final FoodProperties CHICKEN_BURGER_PATTY = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COCOA_SPREAD = food(3, 2).build();
    public static final FoodProperties COCONUT_HALF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COFFEE_BEANS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CORN = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CORN_MEAL = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CRACKED_EGG = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CUCUMBER_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_BEEF_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_BEETROOT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_CARROT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_CHICKEN_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_ONION = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_PORK_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_SCALLION = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_TOMATO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_BREAD = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHILLI_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CINNAMON_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COCOA_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COFFEE_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CURRY_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DICED_CHILLI_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_BASIL = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_BLACK_PEPPER_CLUSTER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_CHILLI_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_CORN = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_CORN_COB = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_MUSTARD_PODS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_TURMERIC_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_VANILLA_PODS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties EGGPLANT_SLICE = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties EGG_YOLK = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties FRIED_EGG = food(2, 2).build();
    public static final FoodProperties GARLIC_CLOVE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GARLIC_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GINGER_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GREEN_OLIVE_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GRILLED_BEEF_BURGER_PATTY = food(3, 2).build();
    public static final FoodProperties GRILLED_CHICKEN_BURGER_PATTY = food(3, 2).build();
    public static final FoodProperties GRILLED_PORK_BURGER_PATTY = food(3, 2).build();
    public static final FoodProperties GROUNDED_ALMOND = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_BASIL = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_BEEF_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_CHICKEN_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_HAZELNUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_PORK_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GROUNDED_WALNUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HAM_SLICE = food(1, 1).build();
    public static final FoodProperties HAZELNUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HOLLOWED_BELL_PEPPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HOLLOWED_EGGPLANT = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HOLLOWED_PORTOBELLO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HOLLOWED_POTATO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties KETCHUP = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LEEK_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LEMON_HALF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LEMON_MARMALADE = food(3, 2).build();
    public static final FoodProperties LEMON_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LETTUCE_LEAF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LIME_HALF = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LIME_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties LIME_MARMALADE = food(3, 2).build();
    public static final FoodProperties MAYO = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MUSTARD = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties OAT_MEAL = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ONION_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ORANGE_HALF = food(1, 1).build();
    public static final FoodProperties ORANGE_SLICE = food(1, 1).build();
    public static final FoodProperties ORANGE_MARMALADE = food(3, 2).build();
    public static final FoodProperties PARSLEY_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PARSLEY_STEM = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEACH_HALF = food(1, 1).build();
    public static final FoodProperties PEACH_SLICE = food(1, 1).build();
    public static final FoodProperties PEACH_MARMALADE = food(3, 2).build();
    public static final FoodProperties PEANUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEANUT_BUTTER = food(3, 3).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEAR_HALF = food(1, 1).build();
    public static final FoodProperties PEAR_SLICE = food(1, 1).build();
    public static final FoodProperties PEAS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEELED_BANANA = food(1, 1).build();
    public static final FoodProperties PEPPER_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PICKED_CHERRY = food(1, 1).build();
    public static final FoodProperties PINEAPPLE_CUTS = food(1, 1).build();
    public static final FoodProperties PINEAPPLE_HALF = food(1, 1).build();
    public static final FoodProperties PINEAPPLE_RINGS = food(1, 1).build();
    public static final FoodProperties PLUM_HALF = food(1, 1).build();
    public static final FoodProperties PLUM_SLICE = food(1, 1).build();
    public static final FoodProperties PLUM_MARMALADE = food(3, 2).build();
    public static final FoodProperties PORK_BURGER_PATTY = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PORTOBELLO_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties POTATO_CUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties POTATO_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RASPBERRY_MARMALADE = food(3, 2).build();
    public static final FoodProperties RAW_BACON = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_BEEF_STEAK = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_CHICKEN_BREAST = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_CHICKEN_DRUMSTICK = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_CHICKEN_WING = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_CORN_COB = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_FISH_FILLET = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_MUTTON_RIBS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_MUTTON_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PORK_RIBS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PORK_STEAK = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_POTATO_FRIES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_RABBIT_LEG = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_RABBIT_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SALMON_FILLET = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_APPLE = food(1, 1).build();
    public static final FoodProperties SHREDDED_CABBAGE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_CARROT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_CUCUMBER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_GINGER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_LETTUCE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_PEAR = food(1, 1).build();
    public static final FoodProperties SHREDDED_POTATO = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SOYBEANS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties STRAWBERRY_MARMALADE = food(3, 2).build();
    public static final FoodProperties STRAWBERRY_SLICE = food(1, 1).build();
    public static final FoodProperties SWEET_CHILLI_SAUCE = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TOMATO_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TURMERIC_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TURMERIC_SLICE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties VANILLA_POWDER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties WALNUTS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties APPLE_YOGURT = food(3, 2).build();
    public static final FoodProperties BANANA_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties BLUEBERRY_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties BLUEBERRY_YOGURT = food(3, 2).build();
    public static final FoodProperties CHERRY_YOGURT = food(3, 2).build();
    public static final FoodProperties CHOCOLATE_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties COCONUT_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties COCONUT_YOGURT = food(3, 2).build();
    public static final FoodProperties CORN_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GRAPE_YOGURT = food(3, 2).build();
    public static final FoodProperties HAZELNUT_YOGURT = food(3, 2).build();
    public static final FoodProperties NUTS_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties ORANGE_YOGURT = food(3, 2).build();
    public static final FoodProperties PASTA_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PEACH_YOGURT = food(3, 2).build();
    public static final FoodProperties PEAR_YOGURT = food(3, 2).build();
    public static final FoodProperties PINEAPPLE_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties PINEAPPLE_YOGURT = food(3, 2).build();
    public static final FoodProperties PLAIN_YOGURT = food(2, 1).build();
    public static final FoodProperties PLUM_YOGURT = food(3, 2).build();
    public static final FoodProperties POTATO_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RASPBERRY_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties RASPBERRY_YOGURT = food(3, 2).build();
    public static final FoodProperties RAW_GNOCCHI = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_LASAGNE_PASTA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_NOODLES_PASTA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_RICE_NOODLES = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PENNE_PASTA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SPAGHETTI_PASTA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_TORTELLINI_PASTA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties STRAWBERRY_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties STRAWBERRY_YOGURT = food(3, 2).build();
    public static final FoodProperties SWEET_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties VEGGIE_JUICE = food(2, 1).build();
    public static final FoodProperties BAKED_RABBIT_LEG = food(2, 2).build();
    public static final FoodProperties BAKED_POTATO_CUTS = food(2, 2).build();
    public static final FoodProperties BOILED_BROCCOLI_CUTS = food(2, 2).build();
    public static final FoodProperties BOILED_CABBAGE_LEAF = food(2, 2).build();
    public static final FoodProperties BOILED_GNOCCHI = food(3, 2).build();
    public static final FoodProperties BOILED_LASAGNE_PASTA = food(3, 2).build();
    public static final FoodProperties BOILED_CARROT_SLICE = food(2, 2).build();
    public static final FoodProperties BOILED_CORN_COB = food(2, 2).build();
    public static final FoodProperties BOILED_LEEK_SLICE = food(2, 1).build();
    public static final FoodProperties BOILED_NOODLES_PASTA = food(3, 2).build();
    public static final FoodProperties BOILED_RICE_NOODLES = food(3, 2).build();
    public static final FoodProperties BOILED_PARSLEY_SLICE = food(2, 1).build();
    public static final FoodProperties BOILED_PEAS = food(1, 1).build();
    public static final FoodProperties BOILED_PENNE_PASTA = food(3, 2).build();
    public static final FoodProperties BOILED_POTATO_CUTS = food(2, 1).build();
    public static final FoodProperties BOILED_SPAGHETTI_PASTA = food(3, 2).build();
    public static final FoodProperties CHOCOLATE_YOGURT = food(3, 2).build();
    public static final FoodProperties COOKED_BACON = food(2, 3).build();
    public static final FoodProperties COOKED_BEEF_SLICE = food(2, 3).build();
    public static final FoodProperties COOKED_BEETROOT_SLICE = food(2, 2).build();
    public static final FoodProperties COOKED_BELL_PEPPER_SLICE = food(2, 2).build();
    public static final FoodProperties COOKED_CHICKEN_BREAST = food(2, 2).build();
    public static final FoodProperties COOKED_CHICKEN_DRUMSTICK = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_BEEF_MEAT = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_BEETROOT = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_CARROT = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_CHICKEN_MEAT = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_PORK_MEAT = food(2, 2).build();
    public static final FoodProperties COOKED_DICED_SCALLION = food(1, 1).build();
    public static final FoodProperties COOKED_DICED_TOMATO = food(2, 2).build();
    public static final FoodProperties COOKED_FISH_FILLET = food(2, 2).build();
    public static final FoodProperties COOKED_FRIES = food(2, 2).build();
    public static final FoodProperties COOKED_GARLIC_SLICE = food(1, 1).build();
    public static final FoodProperties COOKED_LEEK_SLICE = food(2, 2).build();
    public static final FoodProperties COOKED_PORTOBELLO_SLICE = food(2, 2).build();
    public static final FoodProperties COOKED_RABBIT_SLICE = food(2, 2).build();
    public static final FoodProperties COOKED_SALMON_FILLET = food(2, 2).build();
    public static final FoodProperties FRIED_POTATO_SLICE = food(2, 2).build();
    public static final FoodProperties GRILLED_BEEF_STEAK = food(3, 3).build();
    public static final FoodProperties GRILLED_CARROT_SLICE = food(2, 2).build();
    public static final FoodProperties GRILLED_CHICKEN_BREAST = food(2, 3).build();
    public static final FoodProperties GRILLED_CHICKEN_DRUMSTICK = food(2, 3).build();
    public static final FoodProperties GRILLED_CHICKEN_WING = food(2, 2).build();
    public static final FoodProperties GRILLED_CORN_COB = food(2, 2).build();
    public static final FoodProperties GRILLED_EGGPLANT_SLICE = food(3, 2).build();
    public static final FoodProperties GRILLED_FISH_FILLET = food(2, 3).build();
    public static final FoodProperties GRILLED_MUTTON_RIBS = food(3, 3).build();
    public static final FoodProperties GRILLED_MUTTON_SLICE = food(2, 3).build();
    public static final FoodProperties GRILLED_PINEAPPLE_RINGS = food(2, 2).build();
    public static final FoodProperties GRILLED_PORK_RIBS = food(3, 3).build();
    public static final FoodProperties GRILLED_PORK_STEAK = food(3, 3).build();
    public static final FoodProperties GRILLED_SALMON_FILLET = food(2, 3).build();
    public static final FoodProperties GRILLED_TOMATO_SLICE = food(2, 2).build();
    public static final FoodProperties ROASTED_COFFEE_BEANS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ROASTED_PEANUTS = food(2, 1).build();
    public static final FoodProperties TOAST = food(2, 1).build();
    public static final FoodProperties VANILLA_MILKSHAKE = food(1, 1).build();
    public static final FoodProperties VANILLA_YOGURT = food(3, 2).build();
    public static final FoodProperties YEAST = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BEEF_JERKY = food(3, 4).build();
    public static final FoodProperties BOILED_TOMATO = food(2, 2).build();
    public static final FoodProperties BREAD_CRUMBS = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BUTTER = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CAMEMBERT = food(3, 2).build();
    public static final FoodProperties CAMEMBERT_SLICE = food(2, 1).build();
    public static final FoodProperties CHEESE = food(3, 2).build();
    public static final FoodProperties CHEESE_CUTS = food(2, 1).build();
    public static final FoodProperties CHEESE_SLICE = food(2, 1).build();
    public static final FoodProperties CHICKEN_JERKY = food(3, 4).build();
    public static final FoodProperties CREAM = food(1, 1).build();
    public static final FoodProperties CURRED_BEEF_STEAK = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CURRED_CHICKEN_STEAK = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CURRED_PORK_STEAK = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GRILLED_CAMEMBERT = food(4, 3).build();
    public static final FoodProperties PORK_JERKY = food(3, 4).build();
    public static final FoodProperties RICE_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SWEET_RICE_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SHREDDED_CHEESE = food(2, 1).build();
    public static final FoodProperties SHREDDED_GARLIC = food(1, 1).build();
    public static final FoodProperties TOMATO_SAUCE = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties WHIPPED_CREAM = food(1, 2).build();
    public static final FoodProperties BAGUETTE = food(3, 2).build();
    public static final FoodProperties BLUEBERRY_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties BURGER_BUN = food(2, 1).build();
    public static final FoodProperties CARAMEL = food(2, 3).build();
    public static final FoodProperties CARAMEL_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties CHERRY_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties CHOCOLATE_BAR = food(2, 2).build();
    public static final FoodProperties CHOCOLATE_CHIPS = food(1, 1).build();
    public static final FoodProperties CHOCOLATE_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties DRIED_BAGUETTE = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DRIED_ROLL = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GRATED_CHOCOLATE = food(1, 1).build();
    public static final FoodProperties ICE_CREAM = food(3, 1).build();
    public static final FoodProperties LEMON_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties RASPBERRY_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties RAW_BAGUETTE = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_BREAD = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_BURGER_BUN = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_ROLL = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_WAFFLE = food(1, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties ROLL = food(2, 1).build();
    public static final FoodProperties STRACCIATELLA_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties STRAWBERRY_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties VANILLA_ICE_CREAM = food(4, 3).build();
    public static final FoodProperties WAFFLE = food(2, 3).build();
    public static final FoodProperties BOILED_EGG_CUTS = food(2, 1).build();
    public static final FoodProperties CORN_BREAD = food(4, 3).build();
    public static final FoodProperties NACHOS = food(2, 2).build();
    public static final FoodProperties PITA = food(3, 2).build();
    public static final FoodProperties RAW_CORN_BREAD = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_NACHOS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PITA = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_TORTILLA = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties TORTILLA = food(2, 2).build();
    public static final FoodProperties AVOCADO_PESTO = food(4, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PESTO = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BOILED_BEANS = food(2, 2).build();
    public static final FoodProperties COOKED_ONION = food(2, 1).build();
    public static final FoodProperties COOKED_SOY_MEAT = food(2, 2).build();
    public static final FoodProperties RAW_SOY_MEAT = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RICE_DUMPLING_WRAPPER = food(1, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RICE_PAPER = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SOY_FLOUR = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties SPINACH = food(2, 2).build();
    public static final FoodProperties TOFU = food(2, 2).build();
    public static final FoodProperties WHEAT_FLOUR = food(1, 1).build();
    public static final FoodProperties RAW_CHEESE_TORTELLINI = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_MUSHROOM_TORTELLINI = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PORK_TORTELLINI = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SPINACH_TORTELLINI = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties BOILED_CHEESE_TORTELLINI = food(4, 3).build();
    public static final FoodProperties BOILED_MUSHROOM_TORTELLINI = food(4, 3).build();
    public static final FoodProperties BOILED_PORK_TORTELLINI = food(4, 3).build();
    public static final FoodProperties BOILED_SPINACH_TORTELLINI = food(4, 3).build();
    public static final FoodProperties COOKED_GROUNDED_BEEF_MEAT = food(2, 2).build();
    public static final FoodProperties COOKED_GROUNDED_PORK_MEAT = food(2, 2).build();
    public static final FoodProperties MASHED_POTATOES = food(3, 2).build();
    public static final FoodProperties CUPCAKE_BASE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PIE_CRUST = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PIZZA_DOUGH = food(2, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_RICE_CAKE = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RICE_CAKE = food(1, 2).build();
    public static final FoodProperties PEELED_ONION = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties COCONUT_FLAKES = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties FRAPPE_COFFEE = food(2, 2).build();
    public static final FoodProperties VEGETABLE_STOCK_BASE = food(1, 0).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MEAT_STOCK_BASE = food(1, 0).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MEAT_STOCK = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties VEGETABLE_STOCK = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_DELUXE_SKEWER = food(5, 3).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_CHICKEN_SKEWER = food(4, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_PORK_SKEWER = food(4, 3).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_VEGGIE_SKEWER = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties DELUXE_SKEWER = food(7, 8).build();
    public static final FoodProperties CHICKEN_SKEWER = food(6, 6).build();
    public static final FoodProperties PORK_SKEWER = food(6, 7).build();
    public static final FoodProperties VEGGIE_SKEWER = food(5, 5).build();
    public static final FoodProperties RAW_HAM_TOAST = food(4, 2).build();
    public static final FoodProperties HAM_TOAST = food(6, 5).build();
    public static final FoodProperties RAW_BACON_TOAST = food(4, 3).build();
    public static final FoodProperties BACON_TOAST = food(7, 6).build();
    public static final FoodProperties RAW_CHEESY_TOAST = food(4, 4).build();
    public static final FoodProperties CHEESY_TOAST = food(6, 8).build();
    public static final FoodProperties RAW_CHOCOLATE_TOAST = food(3, 3).build();
    public static final FoodProperties CHOCOLATE_TOAST = food(5, 5).build();
    public static final FoodProperties RAW_CHICKEN_TOAST = food(6, 3).build();
    public static final FoodProperties CHICKEN_TOAST = food(7, 5).build();
    public static final FoodProperties HAMBURGER = food(5, 7).build();
    public static final FoodProperties CHEESEBURGER = food(6, 8).build();
    public static final FoodProperties DOUBLE_CHEESEBURGER = food(8, 11).build();
    public static final FoodProperties BACON_BURGER = food(8, 9).build();
    public static final FoodProperties CHICKEN_BURGER = food(7, 8).build();
    public static final FoodProperties COUNTRY_BURGER = food(8, 9).build();
    public static final FoodProperties TOWER_BURGER = food(13, 15).build();
    public static final FoodProperties BIG_PARTY_BURGER = food(12, 13).build();
    public static final FoodProperties VEGGIE_BURGER = food(7, 7).build();
    public static final FoodProperties SAMURAI_BURGER = food(9, 12).build();
    public static final FoodProperties FILET_O_FISH = food(6, 9).build();
    public static final FoodProperties PUMPKIN_SLICE = food(1, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties PUMPKIN_SEEDS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties CHEESE_CURDS = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SAUSAGE = food(3, 2).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties RAW_SALAMI = food(4, 3).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties HARDENED_GELATIN = food(2, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties GELATIN = food(1, 1).effect(HUNGER, PROBABILITY).build();
    public static final FoodProperties MOZZARELLA_CHEESE = food(3, 2).build();
    public static final FoodProperties MOZZARELLA_SLICE = food(2, 1).build();
    public static final FoodProperties FETA_CHEESE = food(3, 3).build();
    public static final FoodProperties FETA_CUTS = food(2, 2).build();
    public static final FoodProperties QUARK = food(2, 3).build();
    public static final FoodProperties RAISINS = food(1, 2).build();
    public static final FoodProperties SAUSAGE = food(4, 4).build();
    public static final FoodProperties SALAMI = food(5, 5).build();
    public static final FoodProperties BOILED_SALAMI = food(4, 4).build();
    public static final FoodProperties SALAMI_SLICE = food(2, 3).build();
    public static final FoodProperties ROASTED_PUMPKIN_SEEDS = food(2, 2).build();

    private static FoodProperties.Builder food(int nutrition, int saturation) {
        return new FoodProperties.Builder().nutrition(nutrition).saturationMod(saturation / (nutrition * 2.0F));
    }

    private FoodList() {
    }

    static {
        FOOD_OVERRIDES.put(Foods.COOKED_BEEF, COOKED_BEEF);
        FOOD_OVERRIDES.put(Foods.CARROT, CARROT);
        FOOD_OVERRIDES.put(Foods.BREAD, BREAD);
        FOOD_OVERRIDES.put(Foods.APPLE, APPLE);
        FOOD_OVERRIDES.put(Foods.GOLDEN_APPLE, GOLDEN_APPLE);
        FOOD_OVERRIDES.put(Foods.ENCHANTED_GOLDEN_APPLE, ENCHANTED_GOLDEN_APPLE);
        FOOD_OVERRIDES.put(Foods.MELON_SLICE, MELON_SLICE);
        FOOD_OVERRIDES.put(Foods.SWEET_BERRIES, SWEET_BERRIES);
        FOOD_OVERRIDES.put(Foods.GLOW_BERRIES, GLOW_BERRIES);
        FOOD_OVERRIDES.put(Foods.CHORUS_FRUIT, CHORUS_FRUIT);
        FOOD_OVERRIDES.put(Foods.GOLDEN_CARROT, GOLDEN_CARROT);
        FOOD_OVERRIDES.put(Foods.POTATO, POTATO);
        FOOD_OVERRIDES.put(Foods.BAKED_POTATO, BAKED_POTATO);
        FOOD_OVERRIDES.put(Foods.POISONOUS_POTATO, POISONOUS_POTATO);
        FOOD_OVERRIDES.put(Foods.BEETROOT, BEETROOT);
        FOOD_OVERRIDES.put(Foods.DRIED_KELP, DRIED_KELP);
        FOOD_OVERRIDES.put(Foods.BEEF, BEEF);
        FOOD_OVERRIDES.put(Foods.PORKCHOP, PORKCHOP);
        FOOD_OVERRIDES.put(Foods.COOKED_PORKCHOP, COOKED_PORKCHOP);
        FOOD_OVERRIDES.put(Foods.MUTTON, MUTTON);
        FOOD_OVERRIDES.put(Foods.COOKED_MUTTON, COOKED_MUTTON);
        FOOD_OVERRIDES.put(Foods.CHICKEN, CHICKEN);
        FOOD_OVERRIDES.put(Foods.COOKED_CHICKEN, COOKED_CHICKEN);
        FOOD_OVERRIDES.put(Foods.RABBIT, RABBIT);
        FOOD_OVERRIDES.put(Foods.COOKED_RABBIT, COOKED_RABBIT);
        FOOD_OVERRIDES.put(Foods.COD, COD);
        FOOD_OVERRIDES.put(Foods.COOKED_COD, COOKED_COD);
        FOOD_OVERRIDES.put(Foods.SALMON, SALMON);
        FOOD_OVERRIDES.put(Foods.COOKED_SALMON, COOKED_SALMON);
        FOOD_OVERRIDES.put(Foods.TROPICAL_FISH, TROPICAL_FISH);
        FOOD_OVERRIDES.put(Foods.COOKIE, COOKIE);
        FOOD_OVERRIDES.put(Foods.PUMPKIN_PIE, PUMPKIN_PIE);
        FOOD_OVERRIDES.put(Foods.ROTTEN_FLESH, ROTTEN_FLESH);
        FOOD_OVERRIDES.put(Foods.SPIDER_EYE, SPIDER_EYE);
        FOOD_OVERRIDES.put(Foods.MUSHROOM_STEW, MUSHROOM_STEW);
        FOOD_OVERRIDES.put(Foods.BEETROOT_SOUP, BEETROOT_SOUP);
        FOOD_OVERRIDES.put(Foods.RABBIT_STEW, RABBIT_STEW);
        FOOD_OVERRIDES.put(Foods.SUSPICIOUS_STEW, SUSPICIOUS_STEW);
        FOOD_OVERRIDES.put(Foods.HONEY_BOTTLE, HONEY_BOTTLE);
    }
}
