package tnt.blockychef.common.init;

import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.ForgeFlowingFluid;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import tnt.blockychef.BlockyChef;

import java.util.function.Supplier;

public final class BlockyChefFluids {

    private static final DeferredRegister<Fluid> REGISTER = DeferredRegister.create(ForgeRegistries.FLUIDS, BlockyChef.MODID);

    public static final RegistryObject<Fluid> ORANGE_FLUID = registerSource("orange", () -> BlockyChefFluids.ORANGE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHERRY_FLUID = registerSource("cherry", () -> BlockyChefFluids.CHERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> OLIVE_OIL_FLUID = registerSource("olive_oil", () -> BlockyChefFluids.OLIVE_OIL_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> OIL_FLUID = registerSource("oil", () -> BlockyChefFluids.OIL_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCONUT_MILK_FLUID = registerSource("coconut_milk", () -> BlockyChefFluids.COCONUT_MILK_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SOY_MILK_FLUID = registerSource("soy_milk", () -> BlockyChefFluids.SOY_MILK_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> APPLE_FLUID = registerSource("apple", () -> BlockyChefFluids.APPLE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_FLUID = registerSource("blueberry", () -> BlockyChefFluids.BLUEBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CARROT_FLUID = registerSource("carrot", () -> BlockyChefFluids.CARROT_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GRAPE_FLUID = registerSource("grape", () -> BlockyChefFluids.GRAPE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LEMON_FLUID = registerSource("lemon", () -> BlockyChefFluids.LEMON_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LIME_FLUID = registerSource("lime", () -> BlockyChefFluids.LIME_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MELON_FLUID = registerSource("melon", () -> BlockyChefFluids.MELON_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEACH_FLUID = registerSource("peach", () -> BlockyChefFluids.PEACH_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEAR_FLUID = registerSource("pear", () -> BlockyChefFluids.PEAR_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_FLUID = registerSource("pineapple", () -> BlockyChefFluids.PINEAPPLE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PLUM_FLUID = registerSource("plum", () -> BlockyChefFluids.PLUM_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_FLUID = registerSource("raspberry", () -> BlockyChefFluids.RASPBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_FLUID = registerSource("strawberry", () -> BlockyChefFluids.STRAWBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SWEET_BERRY_FLUID = registerSource("sweet_berry", () -> BlockyChefFluids.SWEET_BERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_FLUID = registerSource("tomato", () -> BlockyChefFluids.TOMATO_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ORANGE_JUICE_FLUID = registerSource("orange_juice", () -> BlockyChefFluids.ORANGE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> APPLE_JUICE_FLUID = registerSource("apple_juice", () -> BlockyChefFluids.APPLE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_JUICE_FLUID = registerSource("blueberry_juice", () -> BlockyChefFluids.BLUEBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CARROT_JUICE_FLUID = registerSource("carrot_juice", () -> BlockyChefFluids.CARROT_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHERRY_JUICE_FLUID = registerSource("cherry_juice", () -> BlockyChefFluids.CHERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GRAPE_JUICE_FLUID = registerSource("grape_juice", () -> BlockyChefFluids.GRAPE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LEMONADE_FLUID = registerSource("lemonade", () -> BlockyChefFluids.LEMONADE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LIME_JUICE_FLUID = registerSource("lime_juice", () -> BlockyChefFluids.LIME_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MELON_JUICE_FLUID = registerSource("melon_juice", () -> BlockyChefFluids.MELON_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEACH_JUICE_FLUID = registerSource("peach_juice", () -> BlockyChefFluids.PEACH_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEAR_JUICE_FLUID = registerSource("pear_juice", () -> BlockyChefFluids.PEAR_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_JUICE_FLUID = registerSource("pineapple_juice", () -> BlockyChefFluids.PINEAPPLE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PLUM_JUICE_FLUID = registerSource("plum_juice", () -> BlockyChefFluids.PLUM_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_JUICE_FLUID = registerSource("raspberry_juice", () -> BlockyChefFluids.RASPBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_JUICE_FLUID = registerSource("strawberry_juice", () -> BlockyChefFluids.STRAWBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_JUICE_FLUID = registerSource("tomato_juice", () -> BlockyChefFluids.TOMATO_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> VEGGIE_JUICE_FLUID = registerSource("veggie_juice", () -> BlockyChefFluids.VEGGIE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ICE_TEA_FLUID = registerSource("ice_tea", () -> BlockyChefFluids.ICE_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SWEET_BERRY_JUICE_FLUID = registerSource("sweet_berry_juice", () -> BlockyChefFluids.SWEET_BERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BANANA_MILKSHAKE_FLUID = registerSource("banana_milkshake", () -> BlockyChefFluids.BANANA_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_MILKSHAKE_FLUID = registerSource("blueberry_milkshake", () -> BlockyChefFluids.BLUEBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHOCOLATE_MILKSHAKE_FLUID = registerSource("chocolate_milkshake", () -> BlockyChefFluids.CHOCOLATE_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCONUT_MILKSHAKE_FLUID = registerSource("coconut_milkshake", () -> BlockyChefFluids.COCONUT_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> NUTS_MILKSHAKE_FLUID = registerSource("nuts_milkshake", () -> BlockyChefFluids.NUTS_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_MILKSHAKE_FLUID = registerSource("pineapple_milkshake", () -> BlockyChefFluids.PINEAPPLE_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_MILKSHAKE_FLUID = registerSource("raspberry_milkshake", () -> BlockyChefFluids.RASPBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_MILKSHAKE_FLUID = registerSource("strawberry_milkshake", () -> BlockyChefFluids.STRAWBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> VANILLA_MILKSHAKE_FLUID = registerSource("vanilla_milkshake", () -> BlockyChefFluids.VANILLA_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> FRAPPE_COFFEE_FLUID = registerSource("frappe_coffee", () -> BlockyChefFluids.FRAPPE_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ICE_COFFEE_FLUID = registerSource("ice_coffee", () -> BlockyChefFluids.ICE_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEANUT_BUTTER_FLUID = registerSource("peanut_butter", () -> BlockyChefFluids.PEANUT_BUTTER_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCOA_SPREAD_FLUID = registerSource("cocoa_spread", () -> BlockyChefFluids.COCOA_SPREAD_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BBQ_SAUCE_FLUID = registerSource("bbq_sauce", () -> BlockyChefFluids.BBQ_SAUCE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> KETCHUP_FLUID = registerSource("ketchup", () -> BlockyChefFluids.KETCHUP_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_SAUCE_FLUID = registerSource("tomato_sauce", () -> BlockyChefFluids.TOMATO_SAUCE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MAYO_FLUID = registerSource("mayo", () -> BlockyChefFluids.MAYO_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLACK_COFFEE_FLUID = registerSource("black_coffee", () -> BlockyChefFluids.BLACK_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TEA_FLUID = registerSource("tea", () -> BlockyChefFluids.TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BERRY_TEA_FLUID = registerSource("berry_tea", () -> BlockyChefFluids.BERRY_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CITRUS_TEA_FLUID = registerSource("citrus_tea", () -> BlockyChefFluids.CITRUS_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> DANDELION_TEA_FLUID = registerSource("dandelion_tea", () -> BlockyChefFluids.DANDELION_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> FRUIT_TEA_FLUID = registerSource("fruit_tea", () -> BlockyChefFluids.FRUIT_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GINGER_TEA_FLUID = registerSource("ginger_tea", () -> BlockyChefFluids.GINGER_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> HONEY_TEA_FLUID = registerSource("honey_tea", () -> BlockyChefFluids.HONEY_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MILK_TEA_FLUID = registerSource("milk_tea", () -> BlockyChefFluids.MILK_TEA_FLUID_PROPERTIES);



    public static final RegistryObject<Fluid> ORANGE_FLOWING_FLUID = registerSource("orange_flowing", () -> BlockyChefFluids.ORANGE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHERRY_FLOWING_FLUID = registerSource("cherry_flowing", () -> BlockyChefFluids.CHERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> OLIVE_OIL_FLOWING_FLUID = registerSource("olive_oil_flowing", () -> BlockyChefFluids.OLIVE_OIL_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> OIL_FLOWING_FLUID = registerSource("oil_flowing", () -> BlockyChefFluids.OIL_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCONUT_MILK_FLOWING_FLUID = registerSource("coconut_milk_flowing", () -> BlockyChefFluids.COCONUT_MILK_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SOY_MILK_FLOWING_FLUID = registerSource("soy_milk_flowing", () -> BlockyChefFluids.SOY_MILK_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> APPLE_FLOWING_FLUID = registerSource("apple_flowing", () -> BlockyChefFluids.APPLE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_FLOWING_FLUID = registerSource("blueberry_flowing", () -> BlockyChefFluids.BLUEBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CARROT_FLOWING_FLUID = registerSource("carrot_flowing", () -> BlockyChefFluids.CARROT_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GRAPE_FLOWING_FLUID = registerSource("grape_flowing", () -> BlockyChefFluids.GRAPE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LEMON_FLOWING_FLUID = registerSource("lemon_flowing", () -> BlockyChefFluids.LEMON_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LIME_FLOWING_FLUID = registerSource("lime_flowing", () -> BlockyChefFluids.LIME_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MELON_FLOWING_FLUID = registerSource("melon_flowing", () -> BlockyChefFluids.MELON_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEACH_FLOWING_FLUID = registerSource("peach_flowing", () -> BlockyChefFluids.PEACH_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEAR_FLOWING_FLUID = registerSource("pear_flowing", () -> BlockyChefFluids.PEAR_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_FLOWING_FLUID = registerSource("pineapple_flowing", () -> BlockyChefFluids.PINEAPPLE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PLUM_FLOWING_FLUID = registerSource("plum_flowing", () -> BlockyChefFluids.PLUM_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_FLOWING_FLUID = registerSource("raspberry_flowing", () -> BlockyChefFluids.RASPBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_FLOWING_FLUID = registerSource("strawberry_flowing", () -> BlockyChefFluids.STRAWBERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SWEET_BERRY_FLOWING_FLUID = registerSource("sweet_berry_flowing", () -> BlockyChefFluids.SWEET_BERRY_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_FLOWING_FLUID = registerSource("tomato_flowing", () -> BlockyChefFluids.TOMATO_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ORANGE_JUICE_FLOWING_FLUID = registerSource("orange_juice_flowing", () -> BlockyChefFluids.ORANGE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> APPLE_JUICE_FLOWING_FLUID = registerSource("apple_juice_flowing", () -> BlockyChefFluids.APPLE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_JUICE_FLOWING_FLUID = registerSource("blueberry_juice_flowing", () -> BlockyChefFluids.BLUEBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CARROT_JUICE_FLOWING_FLUID = registerSource("carrot_juice_flowing", () -> BlockyChefFluids.CARROT_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHERRY_JUICE_FLOWING_FLUID = registerSource("cherry_juice_flowing", () -> BlockyChefFluids.CHERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GRAPE_JUICE_FLOWING_FLUID = registerSource("grape_juice_flowing", () -> BlockyChefFluids.GRAPE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LEMONADE_FLOWING_FLUID = registerSource("lemonade_flowing", () -> BlockyChefFluids.LEMONADE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> LIME_JUICE_FLOWING_FLUID = registerSource("lime_juice_flowing", () -> BlockyChefFluids.LIME_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MELON_JUICE_FLOWING_FLUID = registerSource("melon_juice_flowing", () -> BlockyChefFluids.MELON_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEACH_JUICE_FLOWING_FLUID = registerSource("peach_juice_flowing", () -> BlockyChefFluids.PEACH_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEAR_JUICE_FLOWING_FLUID = registerSource("pear_juice_flowing", () -> BlockyChefFluids.PEAR_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_JUICE_FLOWING_FLUID = registerSource("pineapple_juice_flowing", () -> BlockyChefFluids.PINEAPPLE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PLUM_JUICE_FLOWING_FLUID = registerSource("plum_juice_flowing", () -> BlockyChefFluids.PLUM_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_JUICE_FLOWING_FLUID = registerSource("raspberry_juice_flowing", () -> BlockyChefFluids.RASPBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_JUICE_FLOWING_FLUID = registerSource("strawberry_juice_flowing", () -> BlockyChefFluids.RASPBERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_JUICE_FLOWING_FLUID = registerSource("tomato_juice_flowing", () -> BlockyChefFluids.TOMATO_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> VEGGIE_JUICE_FLOWING_FLUID = registerSource("veggie_juice_flowing", () -> BlockyChefFluids.VEGGIE_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ICE_TEA_FLOWING_FLUID = registerSource("ice_tea_flowing", () -> BlockyChefFluids.ICE_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> SWEET_BERRY_JUICE_FLOWING_FLUID = registerSource("sweet_berry_juice_flowing", () -> BlockyChefFluids.SWEET_BERRY_JUICE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BANANA_MILKSHAKE_FLOWING_FLUID = registerSource("banana_milkshake_flowing", () -> BlockyChefFluids.BANANA_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLUEBERRY_MILKSHAKE_FLOWING_FLUID = registerSource("blueberry_milkshake_flowing", () -> BlockyChefFluids.BLUEBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CHOCOLATE_MILKSHAKE_FLOWING_FLUID = registerSource("chocolate_milkshake_flowing", () -> BlockyChefFluids.CHOCOLATE_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCONUT_MILKSHAKE_FLOWING_FLUID = registerSource("coconut_milkshake_flowing", () -> BlockyChefFluids.COCONUT_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> NUTS_MILKSHAKE_FLOWING_FLUID = registerSource("nuts_milkshake_flowing", () -> BlockyChefFluids.NUTS_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PINEAPPLE_MILKSHAKE_FLOWING_FLUID = registerSource("pineapple_milkshake_flowing", () -> BlockyChefFluids.PINEAPPLE_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> RASPBERRY_MILKSHAKE_FLOWING_FLUID = registerSource("raspberry_milkshake_flowing", () -> BlockyChefFluids.RASPBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> STRAWBERRY_MILKSHAKE_FLOWING_FLUID = registerSource("strawberry_milkshake_flowing", () -> BlockyChefFluids.STRAWBERRY_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> VANILLA_MILKSHAKE_FLOWING_FLUID = registerSource("vanilla_milkshake_flowing", () -> BlockyChefFluids.VANILLA_MILKSHAKE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> FRAPPE_COFFEE_FLOWING_FLUID = registerSource("frappe_coffee_flowing", () -> BlockyChefFluids.FRAPPE_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> ICE_COFFEE_FLOWING_FLUID = registerSource("ice_coffee_flowing", () -> BlockyChefFluids.ICE_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> PEANUT_BUTTER_FLOWING_FLUID = registerSource("peanut_butter_flowing", () -> BlockyChefFluids.PEANUT_BUTTER_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> COCOA_SPREAD_FLOWING_FLUID = registerSource("cocoa_spread_flowing", () -> BlockyChefFluids.COCOA_SPREAD_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BBQ_SAUCE_FLOWING_FLUID = registerSource("bbq_sauce_flowing", () -> BlockyChefFluids.BBQ_SAUCE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> KETCHUP_FLOWING_FLUID = registerSource("ketchup_flowing", () -> BlockyChefFluids.KETCHUP_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TOMATO_SAUCE_FLOWING_FLUID = registerSource("tomato_sauce_flowing", () -> BlockyChefFluids.TOMATO_SAUCE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MAYO_FLOWING_FLUID = registerSource("mayo_flowing", () -> BlockyChefFluids.MAYO_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BLACK_COFFEE_FLOWING_FLUID = registerSource("black_coffee_flowing", () -> BlockyChefFluids.BLACK_COFFEE_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> TEA_FLOWING_FLUID = registerSource("tea_flowing", () -> BlockyChefFluids.TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> BERRY_TEA_FLOWING_FLUID = registerSource("berry_tea_flowing", () -> BlockyChefFluids.BERRY_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> CITRUS_TEA_FLOWING_FLUID = registerSource("citrus_tea_flowing", () -> BlockyChefFluids.CITRUS_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> DANDELION_TEA_FLOWING_FLUID = registerSource("dandelion_tea_flowing", () -> BlockyChefFluids.DANDELION_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> FRUIT_TEA_FLOWING_FLUID = registerSource("fruit_tea_flowing", () -> BlockyChefFluids.FRUIT_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> GINGER_TEA_FLOWING_FLUID = registerSource("ginger_tea_flowing", () -> BlockyChefFluids.GINGER_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> HONEY_TEA_FLOWING_FLUID = registerSource("honey_tea_flowing", () -> BlockyChefFluids.HONEY_TEA_FLUID_PROPERTIES);
    public static final RegistryObject<Fluid> MILK_TEA_FLOWING_FLUID = registerSource("milk_tea_flowing", () -> BlockyChefFluids.MILK_TEA_FLUID_PROPERTIES);



    private static final ForgeFlowingFluid.Properties ORANGE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.ORANGE_FLUID, ORANGE_FLUID, ORANGE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CHERRY_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CHERRY_FLUID, CHERRY_FLUID, CHERRY_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties OLIVE_OIL_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.OLIVE_OIL_FLUID, OLIVE_OIL_FLUID, OLIVE_OIL_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties OIL_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.OIL_FLUID, OIL_FLUID, OIL_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties COCONUT_MILK_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.COCONUT_MILK_FLUID, COCONUT_MILK_FLUID, COCONUT_MILK_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties SOY_MILK_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.SOY_MILK_FLUID, SOY_MILK_FLUID, SOY_MILK_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties APPLE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.APPLE_FLUID, APPLE_FLUID, APPLE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BLUEBERRY_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BLUEBERRY_FLUID, BLUEBERRY_FLUID, BLUEBERRY_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CARROT_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CARROT_FLUID, CARROT_FLUID, CARROT_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties GRAPE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.GRAPE_FLUID, GRAPE_FLUID, GRAPE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties LEMON_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.LEMON_FLUID, LEMON_FLUID, LEMON_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties LIME_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.LIME_FLUID, LIME_FLUID, LIME_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties MELON_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.MELON_FLUID, MELON_FLUID, MELON_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PEACH_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PEACH_FLUID, PEACH_FLUID, PEACH_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PEAR_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PEAR_FLUID, PEAR_FLUID, PEAR_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PINEAPPLE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PINEAPPLE_FLUID, PINEAPPLE_FLUID, PINEAPPLE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PLUM_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PLUM_FLUID, PLUM_FLUID, PLUM_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties RASPBERRY_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.RASPBERRY_FLUID, RASPBERRY_FLUID, RASPBERRY_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties STRAWBERRY_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.STRAWBERRY_FLUID, STRAWBERRY_FLUID, STRAWBERRY_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties SWEET_BERRY_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.SWEET_BERRY_FLUID, SWEET_BERRY_FLUID, SWEET_BERRY_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties TOMATO_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.TOMATO_FLUID, TOMATO_FLUID, TOMATO_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties ORANGE_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.ORANGE_JUICE_FLUID, ORANGE_JUICE_FLUID, ORANGE_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties APPLE_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.APPLE_JUICE_FLUID, APPLE_JUICE_FLUID, APPLE_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BLUEBERRY_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BLUEBERRY_JUICE_FLUID, BLUEBERRY_JUICE_FLUID, BLUEBERRY_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CARROT_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CARROT_JUICE_FLUID, CARROT_JUICE_FLUID, CARROT_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CHERRY_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CHERRY_JUICE_FLUID, CHERRY_JUICE_FLUID, CHERRY_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties GRAPE_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.GRAPE_JUICE_FLUID, GRAPE_JUICE_FLUID, GRAPE_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties LEMONADE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.LEMONADE_FLUID, LEMONADE_FLUID, LEMONADE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties LIME_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.LIME_JUICE_FLUID, LIME_JUICE_FLUID, LIME_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties MELON_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.MELON_JUICE_FLUID, MELON_JUICE_FLUID, MELON_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PEACH_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PEACH_JUICE_FLUID, PEACH_JUICE_FLUID, PEACH_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PEAR_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PEAR_JUICE_FLUID, PEAR_JUICE_FLUID, PEAR_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PINEAPPLE_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PINEAPPLE_JUICE_FLUID, PINEAPPLE_JUICE_FLUID, PINEAPPLE_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PLUM_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PLUM_JUICE_FLUID, PLUM_JUICE_FLUID, PLUM_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties RASPBERRY_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.RASPBERRY_JUICE_FLUID, RASPBERRY_JUICE_FLUID, RASPBERRY_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties STRAWBERRY_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.STRAWBERRY_JUICE_FLUID, STRAWBERRY_JUICE_FLUID, STRAWBERRY_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties TOMATO_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.TOMATO_JUICE_FLUID, TOMATO_JUICE_FLUID, TOMATO_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties VEGGIE_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.VEGGIE_JUICE_FLUID, VEGGIE_JUICE_FLUID, VEGGIE_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties ICE_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.ICE_TEA_FLUID, ICE_TEA_FLUID, ICE_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties SWEET_BERRY_JUICE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.SWEET_BERRY_JUICE_FLUID, SWEET_BERRY_JUICE_FLUID, SWEET_BERRY_JUICE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BANANA_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BANANA_MILKSHAKE_FLUID, BANANA_MILKSHAKE_FLUID, BANANA_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BLUEBERRY_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BLUEBERRY_MILKSHAKE_FLUID, BLUEBERRY_MILKSHAKE_FLUID, BLUEBERRY_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CHOCOLATE_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CHOCOLATE_MILKSHAKE_FLUID, CHOCOLATE_MILKSHAKE_FLUID, CHOCOLATE_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties COCONUT_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.COCONUT_MILKSHAKE_FLUID, COCONUT_MILKSHAKE_FLUID, COCONUT_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties NUTS_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.NUTS_MILKSHAKE_FLUID, NUTS_MILKSHAKE_FLUID, NUTS_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PINEAPPLE_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PINEAPPLE_MILKSHAKE_FLUID, PINEAPPLE_MILKSHAKE_FLUID, PINEAPPLE_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties RASPBERRY_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.RASPBERRY_MILKSHAKE_FLUID, RASPBERRY_MILKSHAKE_FLUID, RASPBERRY_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties STRAWBERRY_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.STRAWBERRY_MILKSHAKE_FLUID, STRAWBERRY_MILKSHAKE_FLUID, STRAWBERRY_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties VANILLA_MILKSHAKE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.VANILLA_MILKSHAKE_FLUID, VANILLA_MILKSHAKE_FLUID, VANILLA_MILKSHAKE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties FRAPPE_COFFEE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.FRAPPE_COFFEE_FLUID, FRAPPE_COFFEE_FLUID, FRAPPE_COFFEE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties ICE_COFFEE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.ICE_COFFEE_FLUID, ICE_COFFEE_FLUID, ICE_COFFEE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties PEANUT_BUTTER_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.PEANUT_BUTTER_FLUID, PEANUT_BUTTER_FLUID, PEANUT_BUTTER_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties COCOA_SPREAD_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.COCOA_SPREAD_FLUID, COCOA_SPREAD_FLUID, COCOA_SPREAD_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BBQ_SAUCE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BBQ_SAUCE_FLUID, BBQ_SAUCE_FLUID, BBQ_SAUCE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties KETCHUP_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.KETCHUP_FLUID, KETCHUP_FLUID, KETCHUP_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties TOMATO_SAUCE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.TOMATO_SAUCE_FLUID, TOMATO_SAUCE_FLUID, TOMATO_SAUCE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties MAYO_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.MAYO_FLUID, MAYO_FLUID, MAYO_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BLACK_COFFEE_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BLACK_COFFEE_FLUID, BLACK_COFFEE_FLUID, BLACK_COFFEE_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.TEA_FLUID, TEA_FLUID, TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties BERRY_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.BERRY_TEA_FLUID, BERRY_TEA_FLUID, BERRY_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties CITRUS_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.CITRUS_TEA_FLUID, CITRUS_TEA_FLUID, CITRUS_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties DANDELION_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.DANDELION_TEA_FLUID, DANDELION_TEA_FLUID, DANDELION_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties FRUIT_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.FRUIT_TEA_FLUID, FRUIT_TEA_FLUID, FRUIT_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties GINGER_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.GINGER_TEA_FLUID, GINGER_TEA_FLUID, GINGER_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties HONEY_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.HONEY_TEA_FLUID, HONEY_TEA_FLUID, HONEY_TEA_FLOWING_FLUID);
    private static final ForgeFlowingFluid.Properties MILK_TEA_FLUID_PROPERTIES = new ForgeFlowingFluid.Properties(BlockyChefFluidTypes.MILK_TEA_FLUID, MILK_TEA_FLUID, MILK_TEA_FLOWING_FLUID);

    public static void register(IEventBus bus) {
        REGISTER.register(bus);
    }

    private static RegistryObject<Fluid> registerSource(String name, Supplier<ForgeFlowingFluid.Properties> properties) {
        return REGISTER.register(name, () -> new ForgeFlowingFluid.Source(properties.get()));
    }
}
