## Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.21)
forge_version=48.0.24
forge_version_range=[48,)
loader_version_range=[48,)
tntlib_version_range=[0.2.2,2.0)
mapping_channel=parchment
mapping_version=2023.10.08-1.20.2

## Mod
mod_id=blockychef
mod_name=Blockychef
mod_license=All Rights Reserved
mod_version=0.1-dev
mod_group_id=tnt.blockychef
mod_authors=Toma,Tomano
mod_description=Better cooking mod

## Dependencies
tntlib_version=0.4.3
appleskin_version=mc1.20.2-2.5.1
jei_version=16.0.0.28
waila_version=4654448