## Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.0
forge_version_range=[47.4,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03

## Mod
mod_id=blockychef
mod_name=Blockychef
mod_license=All Rights Reserved
mod_version=1.1.1
mod_group_id=tnt.blockychef
mod_authors=Toma,Tomano
mod_description=Advanced cooking mod

## Dependencies
appleskin_version=mc1.20.1-2.5.1
jei_version=15.20.0.108
jade_version=6271651
configuration_version=5840405

## publishing
debug=false
cursegradle_version=1.1.15
project_id=860279