modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="blockychef"
version="${file.jarVersion}"
displayName="Example Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
authors="Toma,Tomano"
description='''
desc
'''

[[dependencies.blockychef]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockychef]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
