package tnt.blockychef.common.registry;

import net.minecraft.core.BlockPos;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.LeavesBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import tnt.blockychef.common.block.*;
import tnt.blockychef.common.init.BlockyChefItems;
import tnt.blockychef.common.init.BlockyChefTrees;
import tnt.blockychef.levelgen.tree.SimpleTreeGrower;

public final class BlockRegistry {

    public static void register(BlockRegistryHelper helper) {
        helper.register("weeds", new DecayingGrowingBlock(BlockBehaviour.Properties.of().noCollission().randomTicks().instabreak().sound(SoundType.CROP)), false);
        helper.register("wheat_crops", new CropsBlock(() -> Items.WHEAT_SEEDS), false);
        helper.register("potato_crops", new CropsBlock(() -> Items.POTATO), false);
        helper.register("carrot_crops", new CropsBlock(() -> Items.CARROT), false);
        helper.register("beetroot_crops", new CropsBlock(() -> Items.BEETROOT_SEEDS), false);
        helper.register("tomato_crops", new CropsBlock(() -> BlockyChefItems.TOMATO), false);
        helper.register("cucumber_crops", new CropsBlock(() -> BlockyChefItems.CUCUMBER), false);
        helper.register("bell_pepper_crops", new CropsBlock(() -> BlockyChefItems.BELL_PEPPER), false);
        helper.register("black_pepper_crops", new CropsBlock(() -> BlockyChefItems.BLACK_PEPPER_CLUSTER), false);
        helper.register("blueberry_crops", new CropsBlock(() -> BlockyChefItems.BLUEBERRY), false);
        helper.register("broccoli_crops", new CropsBlock(() -> BlockyChefItems.BROCCOLI), false);
        helper.register("cabbage_crops", new CropsBlock(() -> BlockyChefItems.CABBAGE), false);
        helper.register("chilli_pepper_crops", new CropsBlock(() -> BlockyChefItems.CHILLI_PEPPER), false);
        helper.register("corn_crops", new CropsBlock(() -> BlockyChefItems.CORN_COB), false);
        helper.register("garlic_crops", new CropsBlock(() -> BlockyChefItems.GARLIC), false);
        helper.register("leek_crops", new CropsBlock(() -> BlockyChefItems.LEEK), false);
        helper.register("lettuce_crops", new CropsBlock(() -> BlockyChefItems.LETTUCE), false);
        helper.register("onion_crops", new CropsBlock(() -> BlockyChefItems.ONION), false);
        helper.register("parsley_crops", new CropsBlock(() -> BlockyChefItems.PARSLEY), false);
        helper.register("raspberry_crops", new CropsBlock(() -> BlockyChefItems.RASPBERRY), false);
        helper.register("spring_onion_crops", new CropsBlock(() -> BlockyChefItems.SPRING_ONION), false);
        helper.register("strawberry_crops", new CropsBlock(() -> BlockyChefItems.STRAWBERRY), false);
        helper.register("turmeric_crops", new CropsBlock(() -> BlockyChefItems.TURMERIC), false);
        helper.register("pineapple_crops", new CropsBlock(() -> BlockyChefItems.PINEAPPLE), false);
        helper.register("portobello_crops", new CropsBlock(() -> BlockyChefItems.PORTOBELLO_MUSHROOM), false);
        helper.register("beans_crops", new CropsBlock(() -> BlockyChefItems.BEAN_POD), false);
        helper.register("peanuts_crops", new CropsBlock(() -> BlockyChefItems.PEANUT), false);
        helper.register("peas_crops", new CropsBlock(() -> BlockyChefItems.PEA_POD), false);
        helper.register("soybeans_crops", new CropsBlock(() -> BlockyChefItems.SOYBEAN_POD), false);
        helper.register("basil_crops", new CropsBlock(() -> BlockyChefItems.BASIL), false);
        helper.register("ginger_crops", new CropsBlock(() -> BlockyChefItems.GINGER_ROOT), false);
        helper.register("tea_crops", new CropsBlock(() -> BlockyChefItems.TEA_LEAF), false);
        helper.register("grapes_crops", new CropsBlock(() -> BlockyChefItems.GRAPES), false);
        helper.register("rice_crops", new CropsBlock(() -> BlockyChefItems.RICE_CROP), false);
        helper.register("oat_crops", new CropsBlock(() -> BlockyChefItems.OAT_CROP), false);
        helper.register("mustard_crops", new CropsBlock(() -> BlockyChefItems.MUSTARD_PODS), false);
        helper.register("coffee_crops", new CropsBlock(() -> BlockyChefItems.COFFEE_BEANS_CLUSTER), false);
        helper.register("eggplant_crops", new CropsBlock(() -> BlockyChefItems.EGGPLANT), false);
        helper.register("spinach_crops", new CropsBlock(() -> BlockyChefItems.SPINACH_LEAF), false);
        helper.register("almond_fruit", new TreeHangingFruitBlock(), false);
        helper.register("apple_fruit", new TreeHangingFruitBlock(), false);
        helper.register("avocado_fruit", new TreeHangingFruitBlock(), false);
        helper.register("banana_fruit", new TreeHangingFruitBlock(), false);
        helper.register("black_olives_fruit", new TreeHangingFruitBlock(), false);
        helper.register("cherry_fruit", new TreeHangingFruitBlock(), false);
        helper.register("coconut_fruit", new TreeHangingFruitBlock(), false);
        helper.register("green_olives_fruit", new TreeHangingFruitBlock(), false);
        helper.register("hazelnut_fruit", new TreeHangingFruitBlock(), false);
        helper.register("lemon_fruit", new TreeHangingFruitBlock(), false);
        helper.register("lime_fruit", new TreeHangingFruitBlock(), false);
        helper.register("orange_fruit", new TreeHangingFruitBlock(), false);
        helper.register("peach_fruit", new TreeHangingFruitBlock(), false);
        helper.register("pear_fruit", new TreeHangingFruitBlock(), false);
        helper.register("plum_fruit", new TreeHangingFruitBlock(), false);
        helper.register("vanilla_fruit", new TreeHangingFruitBlock(), false);
        helper.register("walnut_fruit", new TreeHangingFruitBlock(), false);
        helper.register("drying_rack", new DryingRackBlock());
        helper.register("stove", new StoveBlock());
        helper.register("oak_cutting_board", new CuttingBoardBlock());
        helper.register("spruce_cutting_board", new CuttingBoardBlock());
        helper.register("birch_cutting_board", new CuttingBoardBlock());
        helper.register("jungle_cutting_board", new CuttingBoardBlock());
        helper.register("acacia_cutting_board", new CuttingBoardBlock());
        helper.register("dark_oak_cutting_board", new CuttingBoardBlock());
        helper.register("mangrove_cutting_board", new CuttingBoardBlock());
        helper.register("crimson_cutting_board", new CuttingBoardBlock());
        helper.register("warped_cutting_board", new CuttingBoardBlock());
        helper.register("granite_mortar_and_pestle", new MortarAndPestleBlock());
        helper.register("andesite_mortar_and_pestle", new MortarAndPestleBlock());
        helper.register("diorite_mortar_and_pestle", new MortarAndPestleBlock());
        helper.register("quartz_mortar_and_pestle", new MortarAndPestleBlock());
        helper.register("deepslate_mortar_and_pestle", new MortarAndPestleBlock());
        helper.register("oak_mixing_bowl", new MixingBowlBlock());
        helper.register("spruce_mixing_bowl", new MixingBowlBlock());
        helper.register("birch_mixing_bowl", new MixingBowlBlock());
        helper.register("jungle_mixing_bowl", new MixingBowlBlock());
        helper.register("acacia_mixing_bowl", new MixingBowlBlock());
        helper.register("dark_oak_mixing_bowl", new MixingBowlBlock());
        helper.register("mangrove_mixing_bowl", new MixingBowlBlock());
        helper.register("crimson_mixing_bowl", new MixingBowlBlock());
        helper.register("warped_mixing_bowl", new MixingBowlBlock());
        helper.register("mixer", new MixerBlock());
        helper.register("meat_grinder", new MeatGrinderBlock());
        helper.register("pasta_machine", new PastaMachineBlock());
        helper.register("dough_maker", new DoughMakerBlock());
        helper.register("juicer", new JuicerBlock());
        helper.register("teapot", new TeapotBlock());
        helper.register("acacia_barrel", new BarrelBlock());
        helper.register("birch_barrel", new BarrelBlock());
        helper.register("crimson_barrel", new BarrelBlock());
        helper.register("dark_oak_barrel", new BarrelBlock());
        helper.register("jungle_barrel", new BarrelBlock());
        helper.register("mangrove_barrel", new BarrelBlock());
        helper.register("oak_barrel", new BarrelBlock());
        helper.register("spruce_barrel", new BarrelBlock());
        helper.register("warped_barrel", new BarrelBlock());
        helper.register("toaster", new ToasterBlock());
        helper.register("grill", new GrillBlock());
        helper.register("grater", new GraterBlock());
        helper.register("pot", new PotBlock());
        helper.register("pan", new PanBlock());
        helper.register("saucepan", new SaucepanBlock());
        helper.register("concrete_concrete_kitchen_counter", new KitchenCounterBlock());
        helper.register("concrete_plank_kitchen_counter", new KitchenCounterBlock());
        helper.register("plank_concrete_kitchen_counter", new KitchenCounterBlock());
        helper.register("plank_plank_kitchen_counter", new KitchenCounterBlock());
        helper.register("concrete_concrete_cooking_table", new CookingTableBlock());
        helper.register("concrete_plank_cooking_table", new CookingTableBlock());
        helper.register("plank_concrete_cooking_table", new CookingTableBlock());
        helper.register("plank_plank_cooking_table", new CookingTableBlock());
        helper.register("concrete_kitchen_cabinet", new KitchenCabinetBlock());
        helper.register("plank_kitchen_cabinet", new KitchenCabinetBlock());
        helper.register("concrete_concrete_kitchen_counter_corner", new KitchenCounterCornerBlock());
        helper.register("concrete_plank_kitchen_counter_corner", new KitchenCounterCornerBlock());
        helper.register("plank_concrete_kitchen_counter_corner", new KitchenCounterCornerBlock());
        helper.register("plank_plank_kitchen_counter_corner", new KitchenCounterCornerBlock());
        helper.register("concrete_concrete_kitchen_sink", new KitchenSinkBlock());
        helper.register("concrete_plank_kitchen_sink", new KitchenSinkBlock());
        helper.register("plank_concrete_kitchen_sink", new KitchenSinkBlock());
        helper.register("plank_plank_kitchen_sink", new KitchenSinkBlock());
        helper.register("cinnamon_log", new CinnamonLogBlock(BlockBehaviour.Properties.of().strength(2.0F).sound(SoundType.WOOD)));
        helper.register("cinnamon_stripped_log", new RotatedPillarBlock(BlockBehaviour.Properties.of().strength(2.0F).sound(SoundType.WOOD)));
        helper.register("cinnamon_leaves", new LeavesBlock(BlockBehaviour.Properties.of().strength(0.2F).randomTicks().sound(SoundType.GRASS)
                .noOcclusion().isValidSpawn(BlockRegistry::allowParrotOrOcelotSpawn).isSuffocating(BlockRegistry::alwaysFalse).isViewBlocking(BlockRegistry::alwaysFalse)));
        helper.register("cinnamon_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.CINNAMON_TREE)));
        helper.register("apple_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.APPLE_TREE)));
        helper.register("pear_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.PEAR_TREE)));
        helper.register("orange_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.ORANGE_TREE)));
        helper.register("banana_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.BANANA_TREE)));
        helper.register("almond_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.ALMOND_TREE)));
        helper.register("avocado_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.AVOCADO_TREE)));
        helper.register("black_olives_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.BLACK_OLIVES_TREE)));
        helper.register("green_olives_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.GREEN_OLIVES_TREE)));
        helper.register("lemon_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.LEMON_TREE)));
        helper.register("lime_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.LIME_TREE)));
        helper.register("peach_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.PEACH_TREE)));
        helper.register("coconut_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.COCONUT_TREE)));
        helper.register("vanilla_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.VANILLA_TREE)));
        helper.register("cherry_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.CHERRY_TREE)));
        helper.register("hazelnut_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.HAZELNUT_TREE)));
        helper.register("plum_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.PLUM_TREE)));
        helper.register("walnut_sapling", new TreeSaplingBlock(new SimpleTreeGrower(BlockyChefTrees.WALNUT_TREE)));
        helper.register("salt_ore", new DropExperienceBlock(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 3.0F), UniformInt.of(0, 2)));
    }

    private static boolean allowParrotOrOcelotSpawn(BlockState state, BlockGetter getter, BlockPos pos, EntityType<?> entityType) {
        return entityType == EntityType.OCELOT || entityType == EntityType.PARROT;
    }

    private static boolean alwaysFalse(BlockState state, BlockGetter blockGetter, BlockPos pos) {
        return false;
    }
}
