package tnt.blockychef.common.registry;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.UseAnim;
import net.minecraftforge.registries.RegisterEvent;
import tnt.blockychef.common.food.DrinkList;
import tnt.blockychef.common.food.FoodList;
import tnt.blockychef.common.init.BlockyChefBlocks;
import tnt.blockychef.common.init.BlockyChefItems;
import tnt.blockychef.common.item.*;

public final class ItemRegistry {

    public static void register(RegisterEvent.RegisterHelper<Item> helper) {
        helper.register("tomato", new EdibleCropSeedItem(BlockyChefBlocks.TOMATO_CROPS, new Item.Properties().food(FoodList.TOMATO), DrinkList.TOMATO));
        helper.register("cucumber", new CropSeedsItem(BlockyChefBlocks.CUCUMBER_CROPS, new Item.Properties().food(FoodList.CUCUMBER)));
        helper.register("bell_pepper", new EdibleCropSeedItem(BlockyChefBlocks.BELL_PEPPER_CROPS, new Item.Properties().food(FoodList.BELL_PEPPER), DrinkList.BELL_PEPPER));
        helper.register("black_pepper_cluster", new EdibleCropSeedItem(BlockyChefBlocks.BLACK_PEPPER_CROPS, new Item.Properties().food(FoodList.BLACK_PEPPER), DrinkList.BLACK_PEPPER));
        helper.register("blueberry", new CropSeedsItem(BlockyChefBlocks.BLUEBERRY_CROPS, new Item.Properties().food(FoodList.BLUEBERRY)));
        helper.register("broccoli", new EdibleCropSeedItem(BlockyChefBlocks.BROCCOLI_CROPS, new Item.Properties().food(FoodList.BROCCOLI), DrinkList.BROCCOLI));
        helper.register("cabbage", new EdibleCropSeedItem(BlockyChefBlocks.CABBAGE_CROPS, new Item.Properties().food(FoodList.CABBAGE), DrinkList.CABBAGE));
        helper.register("chilli_pepper", new EdibleCropSeedItem(BlockyChefBlocks.CHILLI_PEPPER_CROPS, new Item.Properties().food(FoodList.CHILLI_PEPPER), DrinkList.CHILLI_PEPPER));
        helper.register("corn_cob", new EdibleCropSeedItem(BlockyChefBlocks.CORN_CROPS, new Item.Properties().food(FoodList.CORN_COB), DrinkList.CORN_COB));
        helper.register("garlic", new EdibleCropSeedItem(BlockyChefBlocks.GARLIC_CROPS, new Item.Properties().food(FoodList.GARLIC), DrinkList.GARLIC));
        helper.register("leek", new EdibleCropSeedItem(BlockyChefBlocks.LEEK_CROPS, new Item.Properties().food(FoodList.LEEK), DrinkList.LEEK));
        helper.register("lettuce", new EdibleCropSeedItem(BlockyChefBlocks.LETTUCE_CROPS, new Item.Properties().food(FoodList.LETTUCE), DrinkList.LETTUCE));
        helper.register("onion", new EdibleCropSeedItem(BlockyChefBlocks.ONION_CROPS, new Item.Properties().food(FoodList.ONION), DrinkList.ONION));
        helper.register("parsley", new EdibleCropSeedItem(BlockyChefBlocks.PARSLEY_CROPS, new Item.Properties().food(FoodList.PARSLEY), DrinkList.PARSLEY));
        helper.register("raspberry", new CropSeedsItem(BlockyChefBlocks.RASPBERRY_CROPS, new Item.Properties().food(FoodList.RASPBERRY)));
        helper.register("spring_onion", new EdibleCropSeedItem(BlockyChefBlocks.SPRING_ONION_CROPS, new Item.Properties().food(FoodList.SPRING_ONION), DrinkList.SPRING_ONION));
        helper.register("strawberry", new CropSeedsItem(BlockyChefBlocks.STRAWBERRY_CROPS, new Item.Properties().food(FoodList.STRAWBERRY)));
        helper.register("turmeric", new EdibleCropSeedItem(BlockyChefBlocks.TURMERIC_CROPS, new Item.Properties().food(FoodList.TURMERIC), DrinkList.TURMERIC));
        helper.register("pineapple", new EdibleCropSeedItem(BlockyChefBlocks.PINEAPPLE_CROPS, new Item.Properties().food(FoodList.PINEAPPLE), DrinkList.PINEAPPLE));
        helper.register("portobello_mushroom", new EdibleCropSeedItem(BlockyChefBlocks.PORTOBELLO_CROPS, new Item.Properties().food(FoodList.PORTOBELLO), DrinkList.PORTOBELLO));
        helper.register("bean_pod", new EdibleCropSeedItem(BlockyChefBlocks.BEANS_CROPS, new Item.Properties().food(FoodList.BEANS_POD), DrinkList.BEANS_POD));
        helper.register("peanut", new EdibleCropSeedItem(BlockyChefBlocks.PEANUTS_CROPS, new Item.Properties().food(FoodList.PEANUT), DrinkList.PEANUT));
        helper.register("pea_pod", new EdibleCropSeedItem(BlockyChefBlocks.PEAS_CROPS, new Item.Properties().food(FoodList.PEA_POD), DrinkList.PEA_POD));
        helper.register("soybean_pod", new EdibleCropSeedItem(BlockyChefBlocks.SOYBEANS_CROPS, new Item.Properties().food(FoodList.SOYBEANS_POD), DrinkList.SOYBEANS_POD));
        helper.register("basil", new EdibleCropSeedItem(BlockyChefBlocks.BASIL_CROPS, new Item.Properties().food(FoodList.BASIL), DrinkList.BASIL));
        helper.register("ginger_root", new EdibleCropSeedItem(BlockyChefBlocks.GINGER_CROPS, new Item.Properties().food(FoodList.GINGER), DrinkList.GINGER));
        helper.register("tea_leaf", new EdibleCropSeedItem(BlockyChefBlocks.TEA_CROPS, new Item.Properties().food(FoodList.TEA_LEAF), DrinkList.TEA_LEAF));
        helper.register("grapes", new EdibleCropSeedItem(BlockyChefBlocks.GRAPES_CROPS, new Item.Properties().food(FoodList.GRAPES), DrinkList.GRAPES));
        helper.register("rice_crop", new EdibleCropSeedItem(BlockyChefBlocks.RICE_CROPS, new Item.Properties().food(FoodList.RICE_CROP), DrinkList.RICE_CROP));
        helper.register("oat_crop", new EdibleCropSeedItem(BlockyChefBlocks.OAT_CROPS, new Item.Properties().food(FoodList.OAT), DrinkList.OAT));
        helper.register("mustard_pods", new EdibleCropSeedItem(BlockyChefBlocks.MUSTARD_CROPS, new Item.Properties().food(FoodList.MUSTARD_PODS), DrinkList.MUSTARD_PODS));
        helper.register("coffee_beans_cluster", new EdibleCropSeedItem(BlockyChefBlocks.COFFEE_CROPS, new Item.Properties().food(FoodList.COFFEE), DrinkList.COFFEE));
        helper.register("eggplant", new EdibleCropSeedItem(BlockyChefBlocks.EGGPLANT_CROPS, new Item.Properties().food(FoodList.EGGPLANT), DrinkList.EGGPLANT));
        helper.register("spinach_leaf", new EdibleCropSeedItem(BlockyChefBlocks.SPINACH_CROPS, new Item.Properties().food(FoodList.SPINACH_LEAF), DrinkList.SPINACH_LEAF));
        helper.register("almond", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ALMOND), DrinkList.ALMOND));
        helper.register("avocado", new DrinkableConsumableItem(new Item.Properties().food(FoodList.AVOCADO), DrinkList.AVOCADO));
        helper.register("banana", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BANANA), DrinkList.BANANA));
        helper.register("black_olives", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BLACK_OLIVES), DrinkList.BLACK_OLIVES));
        helper.register("cherry", new MasteryApplicableItem(new Item.Properties().food(FoodList.CHERRY)));
        helper.register("coconut", new Item(new Item.Properties()));
        helper.register("green_olives", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GREEN_OLIVES), DrinkList.GREEN_OLIVES));
        helper.register("hazelnut", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HAZELNUT), DrinkList.HAZELNUT));
        helper.register("lemon", new MasteryApplicableItem(new Item.Properties().food(FoodList.LEMON)));
        helper.register("lime", new MasteryApplicableItem(new Item.Properties().food(FoodList.LIME)));
        helper.register("orange", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ORANGE), DrinkList.ORANGE));
        helper.register("peach", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEACH)));
        helper.register("pear", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEAR)));
        helper.register("plum", new MasteryApplicableItem(new Item.Properties().food(FoodList.PLUM)));
        helper.register("cinnamon_bark", new MasteryApplicableItem(new Item.Properties()));
        helper.register("vanilla_pods", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VANILLA_PODS), DrinkList.VANILLA_PODS));
        helper.register("walnut", new DrinkableConsumableItem(new Item.Properties().food(FoodList.WALNUT), DrinkList.WALNUT));

        helper.register("shrimp", new MasteryApplicableItem(new Item.Properties().food(FoodList.SHRIMP)));
        helper.register("raw_shrimp", new MasteryApplicableItem(new Item.Properties().food(FoodList.RAW_SHRIMP)));
        helper.register("fried_shrimp", new DrinkableConsumableItem(new Item.Properties().food(FoodList.FRIED_SHRIMP), DrinkList.FRIED_SHRIMP));
        helper.register("burnt_shrimp", new MasteryApplicableItem(new Item.Properties()));

        helper.register("apple_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.APPLE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("apple_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.APPLE_HALF)));
        helper.register("apple_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.APPLE_MARMALADE), DrinkList.APPLE_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("apple_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.APPLE_SLICE)));
        helper.register("avocado_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.AVOCADO_SLICE), DrinkList.AVOCADO_SLICE));
        helper.register("banana_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BANANA_SLICE), DrinkList.BANANA_SLICE));
        helper.register("bbq_sauce", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BBQ_SAUCE), DrinkList.BBQ_SAUCE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("beans", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BEANS), DrinkList.BEANS));
        helper.register("beef_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BEEF_BURGER_PATTY), DrinkList.BEEF_BURGER_PATTY));
        helper.register("beef_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.BEEF_SLICE)));
        helper.register("beetroot_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.BEETROOT_SLICE)));
        helper.register("bell_pepper_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BELL_PEPPER_SLICE), DrinkList.BELL_PEPPER_SLICE));
        helper.register("black_olive_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BLACK_OLIVE_SLICE), DrinkList.BLACK_OLIVE_SLICE));
        helper.register("blueberry_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BLUEBERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("blueberry_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BLUEBERRY_MARMALADE), DrinkList.BLUEBERRY_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("boiled_rice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_RICE), DrinkList.BOILED_RICE));
        helper.register("bread_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BREAD_SLICE), DrinkList.BREAD_SLICE));
        helper.register("broccoli_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BROCCOLI_CUTS), DrinkList.BROCCOLI_CUTS));
        helper.register("burnt_beef_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_chicken_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_pork_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_rice", new Item(new Item.Properties()));
        helper.register("burnt_grounded_pork_meat", new Item(new Item.Properties()));
        helper.register("burnt_grounded_beef_meat", new Item(new Item.Properties()));
        helper.register("cabbage_leaf", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CABBAGE_LEAF), DrinkList.CABBAGE_LEAF));
        helper.register("carrot_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CARROT_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("carrot_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CARROT_SLICE), DrinkList.CARROT_SLICE));
        helper.register("cherry_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CHERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("cherry_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHERRY_MARMALADE), DrinkList.CHERRY_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("chicken_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHICKEN_BURGER_PATTY), DrinkList.CHICKEN_BURGER_PATTY));
        helper.register("chilli_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHILLI_POWDER), DrinkList.CHILLI_POWDER));
        helper.register("cinnamon_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CINNAMON_POWDER), DrinkList.CINNAMON_POWDER));
        helper.register("cocoa_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COCOA_POWDER), DrinkList.COCOA_POWDER));
        helper.register("cocoa_spread", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COCOA_SPREAD), DrinkList.COCOA_SPREAD));
        helper.register("coconut_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.COCONUT_HALF)));
        helper.register("coconut_milk", new DrinkableConsumableItem(new Item.Properties(), DrinkList.COCONUT_MILK, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("coffee_beans", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COFFEE_BEANS), DrinkList.COFFEE_BEANS));
        helper.register("coffee_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COFFEE_POWDER), DrinkList.COFFEE_POWDER));
        helper.register("corn", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CORN), DrinkList.CORN));
        helper.register("corn_meal", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CORN_MEAL), DrinkList.CORN_MEAL));
        helper.register("cracked_egg", new MasteryApplicableItem(new Item.Properties().food(FoodList.CRACKED_EGG)));
        helper.register("cucumber_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.CUCUMBER_SLICE)));
        helper.register("curry_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CURRY_POWDER), DrinkList.CURRY_POWDER));
        helper.register("diced_beef_meat", new MasteryApplicableItem(new Item.Properties().food(FoodList.DICED_BEEF_MEAT)));
        helper.register("diced_beetroot", new MasteryApplicableItem(new Item.Properties().food(FoodList.DICED_BEETROOT)));
        helper.register("diced_carrot", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DICED_CARROT), DrinkList.DICED_CARROT));
        helper.register("diced_chicken_meat", new MasteryApplicableItem(new Item.Properties().food(FoodList.DICED_CHICKEN_MEAT)));
        helper.register("diced_chilli_pepper", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DICED_CHILLI_PEPPER), DrinkList.DICED_CHILLI_PEPPER));
        helper.register("diced_onion", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DICED_ONION), DrinkList.DICED_ONION));
        helper.register("diced_pork_meat", new MasteryApplicableItem(new Item.Properties().food(FoodList.DICED_PORK_MEAT)));
        helper.register("diced_scallion", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DICED_SCALLION), DrinkList.DICED_SCALLION));
        helper.register("diced_tomato", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DICED_TOMATO), DrinkList.DICED_TOMATO));
        helper.register("dried_basil", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_BASIL), DrinkList.DRIED_BASIL));
        helper.register("dried_black_pepper_cluster", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_BLACK_PEPPER_CLUSTER), DrinkList.DRIED_BLACK_PEPPER_CLUSTER));
        helper.register("dried_bread", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_BREAD), DrinkList.DRIED_BREAD));
        helper.register("dried_chilli_pepper", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_CHILLI_PEPPER), DrinkList.DRIED_CHILLI_PEPPER));
        helper.register("dried_cinnamon_bark", new Item(new Item.Properties()));
        helper.register("dried_corn", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_CORN), DrinkList.DRIED_CORN));
        helper.register("dried_corn_cob", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_CORN_COB), DrinkList.DRIED_CORN_COB));
        helper.register("dried_mustard_pods", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_MUSTARD_PODS), DrinkList.DRIED_MUSTARD_PODS));
        helper.register("dried_turmeric_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_TURMERIC_SLICE), DrinkList.DRIED_TURMERIC_SLICE));
        helper.register("dried_vanilla_pods", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_VANILLA_PODS), DrinkList.DRIED_VANILLA_PODS));
        helper.register("eggplant_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.EGGPLANT_SLICE), DrinkList.EGGPLANT_SLICE));
        helper.register("egg_yolk", new MasteryApplicableItem(new Item.Properties().food(FoodList.EGG_YOLK)));
        helper.register("empty_bottle", new FillableBottleItem(new Item.Properties()).fillMilkFromEntity(() -> new ItemStack(BlockyChefItems.MILK)).fillWaterFromSource(() -> new ItemStack(BlockyChefItems.BOTTLE_OF_WATER)));
        helper.register("empty_jar", new Item(new Item.Properties()));
        helper.register("fried_egg", new DrinkableConsumableItem(new Item.Properties().food(FoodList.FRIED_EGG), DrinkList.FRIED_EGG));
        helper.register("garlic_clove", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GARLIC_CLOVE), DrinkList.GARLIC_CLOVE));
        helper.register("garlic_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GARLIC_SLICE), DrinkList.GARLIC_SLICE));
        helper.register("ginger_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GINGER_SLICE), DrinkList.GINGER_SLICE));
        helper.register("grape_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.GRAPE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("green_olive_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GREEN_OLIVE_SLICE), DrinkList.GREEN_OLIVE_SLICE));
        helper.register("grilled_beef_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_BEEF_BURGER_PATTY), DrinkList.GRILLED_BEEF_BURGER_PATTY));
        helper.register("grilled_chicken_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CHICKEN_BURGER_PATTY), DrinkList.GRILLED_CHICKEN_BURGER_PATTY));
        helper.register("grilled_pork_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_PORK_BURGER_PATTY), DrinkList.GRILLED_PORK_BURGER_PATTY));
        helper.register("grounded_almond", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_ALMOND), DrinkList.GROUNDED_ALMOND));
        helper.register("grounded_basil", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_BASIL), DrinkList.GROUNDED_BASIL));
        helper.register("grounded_beef_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_BEEF_MEAT), DrinkList.GROUNDED_BEEF_MEAT));
        helper.register("grounded_chicken_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_CHICKEN_MEAT), DrinkList.GROUNDED_CHICKEN_MEAT));
        helper.register("grounded_hazelnuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_HAZELNUTS), DrinkList.GROUNDED_HAZELNUTS));
        helper.register("grounded_pork_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_PORK_MEAT), DrinkList.GROUNDED_PORK_MEAT));
        helper.register("grounded_walnuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GROUNDED_WALNUTS), DrinkList.GROUNDED_WALNUTS));
        helper.register("ham_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HAM_SLICE), DrinkList.HAM_SLICE));
        helper.register("hazelnuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HAZELNUTS), DrinkList.HAZELNUTS));
        helper.register("hollowed_bell_pepper", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_BELL_PEPPER), DrinkList.HOLLOWED_BELL_PEPPER));
        helper.register("hollowed_eggplant", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_EGGPLANT), DrinkList.HOLLOWED_EGGPLANT));
        helper.register("hollowed_portobello", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_PORTOBELLO), DrinkList.HOLLOWED_PORTOBELLO));
        helper.register("hollowed_potato", new DrinkableConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_POTATO), DrinkList.HOLLOWED_POTATO));
        helper.register("ketchup", new DrinkableConsumableItem(new Item.Properties().food(FoodList.KETCHUP), DrinkList.KETCHUP).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("leek_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.LEEK_SLICE), DrinkList.LEEK_SLICE));
        helper.register("lemon_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.LEMON_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("lemon_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.LEMON_HALF)));
        helper.register("lemon_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.LEMON_MARMALADE), DrinkList.LEMON_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("lemon_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.LEMON_SLICE)));
        helper.register("lettuce_leaf", new DrinkableConsumableItem(new Item.Properties().food(FoodList.LETTUCE_LEAF), DrinkList.LETTUCE_LEAF));
        helper.register("lime_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.LIME_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("lime_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.LIME_HALF)));
        helper.register("lime_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.LIME_MARMALADE), DrinkList.LIME_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("lime_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.LIME_SLICE)));
        helper.register("mayo", new DrinkableConsumableItem(new Item.Properties().food(FoodList.MAYO), DrinkList.MAYO).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("melon_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.MELON_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("mustard", new DrinkableConsumableItem(new Item.Properties().food(FoodList.MUSTARD), DrinkList.MUSTARD).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("oat_meal", new DrinkableConsumableItem(new Item.Properties().food(FoodList.OAT_MEAL), DrinkList.OAT_MEAL));
        helper.register("oil", new DrinkableConsumableItem(new Item.Properties(), DrinkList.OIL, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("olive_oil", new DrinkableConsumableItem(new Item.Properties(), DrinkList.OLIVE_OIL, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("onion_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ONION_SLICE), DrinkList.ONION_SLICE));
        helper.register("orange_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.ORANGE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("orange_half", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ORANGE_HALF), DrinkList.ORANGE_HALF));
        helper.register("orange_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ORANGE_MARMALADE), DrinkList.ORANGE_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("orange_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ORANGE_SLICE), DrinkList.ORANGE_SLICE));
        helper.register("parsley_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PARSLEY_SLICE), DrinkList.PARSLEY_SLICE));
        helper.register("parsley_stem", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PARSLEY_STEM), DrinkList.PARSLEY_STEM));
        helper.register("peach_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PEACH_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("peach_half", new Item(new Item.Properties().food(FoodList.PEACH_HALF)));
        helper.register("peach_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEACH_MARMALADE), DrinkList.PEACH_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("peach_slice", new Item(new Item.Properties().food(FoodList.PEACH_SLICE)));
        helper.register("peanuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEANUTS), DrinkList.PEANUTS));
        helper.register("peanut_butter", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEANUT_BUTTER), DrinkList.PEANUT_BUTTER).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("pear_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PEAR_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("pear_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEAR_HALF)));
        helper.register("pear_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEAR_SLICE)));
        helper.register("peas", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEAS), DrinkList.PEAS));
        helper.register("peeled_banana", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEELED_BANANA), DrinkList.PEELED_BANANA));
        helper.register("pepper_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEPPER_POWDER), DrinkList.PEPPER_POWDER));
        helper.register("picked_cherry", new MasteryApplicableItem(new Item.Properties().food(FoodList.PICKED_CHERRY)));
        helper.register("pineapple_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_CUTS), DrinkList.PINEAPPLE_CUTS));
        helper.register("pineapple_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PINEAPPLE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("pineapple_half", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_HALF), DrinkList.PINEAPPLE_HALF));
        helper.register("pineapple_rings", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_RINGS), DrinkList.PINEAPPLE_RINGS));
        helper.register("plum_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PLUM_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("plum_half", new MasteryApplicableItem(new Item.Properties().food(FoodList.PLUM_HALF)));
        helper.register("plum_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PLUM_MARMALADE), DrinkList.PLUM_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("plum_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.PLUM_SLICE)));
        helper.register("pork_burger_patty", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PORK_BURGER_PATTY), DrinkList.PORK_BURGER_PATTY));
        helper.register("portobello_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PORTOBELLO_SLICE), DrinkList.PORTOBELLO_SLICE));
        helper.register("potato_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.POTATO_CUTS), DrinkList.POTATO_CUTS));
        helper.register("potato_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.POTATO_SLICE), DrinkList.POTATO_SLICE));
        helper.register("raspberry_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.RASPBERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("raspberry_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RASPBERRY_MARMALADE), DrinkList.RASPBERRY_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("raw_bacon", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_BACON), DrinkList.RAW_BACON));
        helper.register("raw_beef_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_BEEF_STEAK), DrinkList.RAW_BEEF_STEAK));
        helper.register("raw_chicken_breast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CHICKEN_BREAST), DrinkList.RAW_CHICKEN_BREAST));
        helper.register("raw_chicken_drumstick", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CHICKEN_DRUMSTICK), DrinkList.RAW_CHICKEN_DRUMSTICK));
        helper.register("raw_chicken_wing", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CHICKEN_WING), DrinkList.RAW_CHICKEN_WING));
        helper.register("raw_corn_cob", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CORN_COB), DrinkList.RAW_CORN_COB));
        helper.register("raw_fish_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_FISH_FILLET), DrinkList.RAW_FISH_FILLET));
        helper.register("raw_mutton_ribs", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_MUTTON_RIBS), DrinkList.RAW_MUTTON_RIBS));
        helper.register("raw_mutton_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_MUTTON_SLICE), DrinkList.RAW_MUTTON_SLICE));
        helper.register("raw_pork_ribs", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PORK_RIBS), DrinkList.RAW_PORK_RIBS));
        helper.register("raw_pork_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PORK_STEAK), DrinkList.RAW_PORK_STEAK));
        helper.register("raw_potato_fries", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_POTATO_FRIES), DrinkList.RAW_POTATO_FRIES));
        helper.register("raw_rabbit_leg", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_RABBIT_LEG), DrinkList.RAW_RABBIT_LEG));
        helper.register("raw_rabbit_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_RABBIT_SLICE), DrinkList.RAW_RABBIT_SLICE));
        helper.register("raw_salmon_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_SALMON_FILLET), DrinkList.RAW_SALMON_FILLET));
        helper.register("rice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RICE), DrinkList.RICE));
        helper.register("sake", new DrinkableConsumableItem(new Item.Properties(), DrinkList.SAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("salt", new Item(new Item.Properties()));
        helper.register("shredded_apple", new MasteryApplicableItem(new Item.Properties().food(FoodList.SHREDDED_APPLE)));
        helper.register("shredded_cabbage", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_CABBAGE), DrinkList.SHREDDED_CABBAGE));
        helper.register("shredded_carrot", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_CARROT), DrinkList.SHREDDED_CARROT));
        helper.register("shredded_cucumber", new MasteryApplicableItem(new Item.Properties().food(FoodList.SHREDDED_CUCUMBER)));
        helper.register("shredded_ginger", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_GINGER), DrinkList.SHREDDED_GINGER));
        helper.register("shredded_lettuce", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_LETTUCE), DrinkList.SHREDDED_LETTUCE));
        helper.register("shredded_pear", new MasteryApplicableItem(new Item.Properties().food(FoodList.SHREDDED_PEAR)));
        helper.register("shredded_potato", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_POTATO), DrinkList.SHREDDED_POTATO));
        helper.register("soybeans", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SOYBEANS), DrinkList.SOYBEANS));
        helper.register("soy_milk", new DrinkableConsumableItem(new Item.Properties(), DrinkList.SOY_MILK, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("soy_sauce", new DrinkableConsumableItem(new Item.Properties(), DrinkList.SOY_SAUCE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("strawberry_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.STRAWBERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("strawberry_marmalade", new DrinkableConsumableItem(new Item.Properties().food(FoodList.STRAWBERRY_MARMALADE), DrinkList.STRAWBERRY_MARMALADE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("strawberry_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.STRAWBERRY_SLICE)));
        helper.register("sweet_berry_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.SWEET_BERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("sweet_chilli_sauce", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SWEET_CHILLI_SAUCE), DrinkList.SWEET_CHILLI_SAUCE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("tomato_extract", new DrinkableConsumableItem(new Item.Properties(), DrinkList.TOMATO_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("tomato_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TOMATO_SLICE), DrinkList.TOMATO_SLICE));
        helper.register("turmeric_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TURMERIC_POWDER), DrinkList.TURMERIC_POWDER));
        helper.register("turmeric_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TURMERIC_SLICE), DrinkList.TURMERIC_SLICE));
        helper.register("vanilla_powder", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VANILLA_POWDER), DrinkList.VANILLA_POWDER));
        helper.register("vinegar", new DrinkableConsumableItem(new Item.Properties(), DrinkList.VINEGAR, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("walnuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.WALNUTS), DrinkList.WALNUTS));
        helper.register("wine", new DrinkableConsumableItem(new Item.Properties(), DrinkList.WINE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("apple_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.APPLE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("apple_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.APPLE_YOGURT)));
        helper.register("banana_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BANANA_MILKSHAKE), DrinkList.BANANA_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("vegetable_stock_base", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VEGETABLE_STOCK_BASE), DrinkList.VEGETABLE_STOCK_BASE, UseAnim.DRINK).returns(() -> Items.BOWL));
        helper.register("vegetable_stock", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VEGETABLE_STOCK), DrinkList.VEGETABLE_STOCK, UseAnim.DRINK).returns(() -> Items.BOWL));
        helper.register("meat_stock_base", new DrinkableConsumableItem(new Item.Properties().food(FoodList.MEAT_STOCK_BASE), DrinkList.MEAT_STOCK_BASE, UseAnim.DRINK).returns(() -> Items.BOWL));
        helper.register("meat_stock", new DrinkableConsumableItem(new Item.Properties().food(FoodList.MEAT_STOCK), DrinkList.MEAT_STOCK, UseAnim.DRINK).returns(() -> Items.BOWL));
        helper.register("raw_deluxe_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_DELUXE_SKEWER), DrinkList.RAW_DELUXE_SKEWER).returns(() -> Items.STICK));
        helper.register("raw_chicken_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CHICKEN_SKEWER), DrinkList.RAW_CHICKEN_SKEWER).returns(() -> Items.STICK));
        helper.register("raw_pork_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PORK_SKEWER), DrinkList.RAW_PORK_SKEWER).returns(() -> Items.STICK));
        helper.register("raw_veggie_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_VEGGIE_SKEWER), DrinkList.RAW_VEGGIE_SKEWER).returns(() -> Items.STICK));
        helper.register("deluxe_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DELUXE_SKEWER), DrinkList.DELUXE_SKEWER).returns(() -> Items.STICK));
        helper.register("chicken_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHICKEN_SKEWER), DrinkList.CHICKEN_SKEWER).returns(() -> Items.STICK));
        helper.register("pork_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PORK_SKEWER), DrinkList.PORK_SKEWER).returns(() -> Items.STICK));
        helper.register("veggie_skewer", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VEGGIE_SKEWER), DrinkList.VEGGIE_SKEWER).returns(() -> Items.STICK));
        helper.register("blueberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BLUEBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("blueberry_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BLUEBERRY_MILKSHAKE), DrinkList.BLUEBERRY_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("blueberry_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.BLUEBERRY_YOGURT)));
        helper.register("carrot_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CARROT_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("cherry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CHERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("cherry_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.CHERRY_YOGURT)));
        helper.register("chocolate_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHOCOLATE_MILKSHAKE), DrinkList.CHOCOLATE_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("coconut_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COCONUT_MILKSHAKE), DrinkList.COCONUT_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("coconut_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.COCONUT_YOGURT)));
        helper.register("corn_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CORN_DOUGH), DrinkList.CORN_DOUGH));
        helper.register("dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DOUGH), DrinkList.DOUGH));
        helper.register("empty_glass", new MasteryApplicableItem(new Item.Properties()));
        helper.register("empty_large_glass", new MasteryApplicableItem(new Item.Properties()));
        helper.register("grape_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.GRAPE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("grape_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.GRAPE_YOGURT)));
        helper.register("hazelnut_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.HAZELNUT_YOGURT)));
        helper.register("lemonade", new DrinkableConsumableItem(new Item.Properties(), DrinkList.LEMONADE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("lime_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.LIME_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("melon_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.MELON_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("nuts_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.NUTS_MILKSHAKE), DrinkList.NUTS_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("orange_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.ORANGE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("orange_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.ORANGE_YOGURT)));
        helper.register("pasta_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PASTA_DOUGH), DrinkList.PASTA_DOUGH));
        helper.register("peach_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PEACH_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("peach_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEACH_YOGURT)));
        helper.register("pear_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PEAR_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("pear_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.PEAR_YOGURT)));
        helper.register("pineapple_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PINEAPPLE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("pineapple_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_MILKSHAKE), DrinkList.PINEAPPLE_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("pineapple_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.PINEAPPLE_YOGURT)));
        helper.register("plain_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.PLAIN_YOGURT)));
        helper.register("plum_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.PLUM_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("plum_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.PLUM_YOGURT)));
        helper.register("potato_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.POTATO_DOUGH), DrinkList.POTATO_DOUGH));
        helper.register("raspberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.RASPBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("raspberry_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RASPBERRY_MILKSHAKE), DrinkList.RASPBERRY_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("raspberry_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.RASPBERRY_YOGURT)));
        helper.register("raw_gnocchi", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_GNOCCHI), DrinkList.RAW_GNOCCHI));
        helper.register("raw_lasagne_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_LASAGNE_PASTA), DrinkList.RAW_LASAGNE_PASTA));
        helper.register("raw_noodles_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_NOODLES_PASTA), DrinkList.RAW_NOODLES_PASTA));
        helper.register("raw_rice_noodles", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_RICE_NOODLES), DrinkList.RAW_RICE_NOODLES));
        helper.register("raw_penne_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PENNE_PASTA), DrinkList.RAW_PENNE_PASTA));
        helper.register("raw_spaghetti_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_SPAGHETTI_PASTA), DrinkList.RAW_SPAGHETTI_PASTA));
        helper.register("raw_tortellini_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_TORTELLINI_PASTA), DrinkList.RAW_TORTELLINI_PASTA));
        helper.register("strawberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.STRAWBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("strawberry_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.STRAWBERRY_MILKSHAKE), DrinkList.STRAWBERRY_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("strawberry_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.STRAWBERRY_YOGURT)));
        helper.register("sweet_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SWEET_DOUGH), DrinkList.SWEET_DOUGH));
        helper.register("tomato_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.TOMATO_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("veggie_juice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VEGGIE_JUICE), DrinkList.VEGGIE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("baked_rabbit_leg", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BAKED_RABBIT_LEG), DrinkList.BAKED_RABBIT_LEG));
        helper.register("baked_potato_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BAKED_POTATO_CUTS), DrinkList.BAKED_POTATO_CUTS));
        helper.register("boiled_broccoli_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_BROCCOLI_CUTS), DrinkList.BOILED_BROCCOLI_CUTS));
        helper.register("boiled_cabbage_leaf", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_CABBAGE_LEAF), DrinkList.BOILED_CABBAGE_LEAF));
        helper.register("boiled_carrot_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_CARROT_SLICE), DrinkList.BOILED_CARROT_SLICE));
        helper.register("boiled_corn_cob", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_CORN_COB), DrinkList.BOILED_CORN_COB));
        helper.register("boiled_gnocchi", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_GNOCCHI), DrinkList.BOILED_GNOCCHI));
        helper.register("boiled_lasagne_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_LASAGNE_PASTA), DrinkList.BOILED_LASAGNE_PASTA));
        helper.register("boiled_leek_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_LEEK_SLICE), DrinkList.BOILED_LEEK_SLICE));
        helper.register("boiled_noodles_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_NOODLES_PASTA), DrinkList.BOILED_NOODLES_PASTA));
        helper.register("boiled_rice_noodles", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_RICE_NOODLES), DrinkList.BOILED_RICE_NOODLES));
        helper.register("boiled_parsley_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_PARSLEY_SLICE), DrinkList.BOILED_PARSLEY_SLICE));
        helper.register("boiled_peas", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_PEAS), DrinkList.BOILED_PEAS));
        helper.register("boiled_penne_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_PENNE_PASTA), DrinkList.BOILED_PENNE_PASTA));
        helper.register("boiled_potato_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_POTATO_CUTS), DrinkList.BOILED_POTATO_CUTS));
        helper.register("boiled_spaghetti_pasta", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_SPAGHETTI_PASTA), DrinkList.BOILED_SPAGHETTI_PASTA));
        helper.register("burnt_bacon", new Item(new Item.Properties()));
        helper.register("burnt_beef_slice", new Item(new Item.Properties()));
        helper.register("burnt_beef_steak", new Item(new Item.Properties()));
        helper.register("burnt_beetroot_slice", new Item(new Item.Properties()));
        helper.register("burnt_bell_pepper_slice", new Item(new Item.Properties()));
        helper.register("burnt_broccoli_cuts", new Item(new Item.Properties()));
        helper.register("burnt_cabbage_leaf", new Item(new Item.Properties()));
        helper.register("burnt_carrot_slice", new Item(new Item.Properties()));
        helper.register("burnt_chicken_breast", new Item(new Item.Properties()));
        helper.register("burnt_chicken_drumstick", new Item(new Item.Properties()));
        helper.register("burnt_chicken_wing", new Item(new Item.Properties()));
        helper.register("burnt_coffee_beans", new Item(new Item.Properties()));
        helper.register("burnt_corn_cob", new Item(new Item.Properties()));
        helper.register("burnt_diced_beef_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_beetroot", new Item(new Item.Properties()));
        helper.register("burnt_diced_carrot", new Item(new Item.Properties()));
        helper.register("burnt_diced_chicken_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_pork_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_scallion", new Item(new Item.Properties()));
        helper.register("burnt_diced_tomato", new Item(new Item.Properties()));
        helper.register("burnt_eggplant_slice", new Item(new Item.Properties()));
        helper.register("burnt_fish_fillet", new Item(new Item.Properties()));
        helper.register("burnt_fried_egg", new Item(new Item.Properties()));
        helper.register("burnt_fries", new Item(new Item.Properties()));
        helper.register("burnt_garlic_slice", new Item(new Item.Properties()));
        helper.register("burnt_gnocchi", new Item(new Item.Properties()));
        helper.register("burnt_lasagne_pasta", new Item(new Item.Properties()));
        helper.register("burnt_leek_slice", new Item(new Item.Properties()));
        helper.register("burnt_mutton_ribs", new Item(new Item.Properties()));
        helper.register("burnt_mutton_slice", new Item(new Item.Properties()));
        helper.register("burnt_noodles_pasta", new Item(new Item.Properties()));
        helper.register("burnt_rice_noodles", new Item(new Item.Properties()));
        helper.register("burnt_parsley_slice", new Item(new Item.Properties()));
        helper.register("burnt_peanuts", new Item(new Item.Properties()));
        helper.register("burnt_peas", new Item(new Item.Properties()));
        helper.register("burnt_penne_pasta", new Item(new Item.Properties()));
        helper.register("burnt_pineapple_rings", new Item(new Item.Properties()));
        helper.register("burnt_pork_ribs", new Item(new Item.Properties()));
        helper.register("burnt_pork_steak", new Item(new Item.Properties()));
        helper.register("burnt_portobello_slice", new Item(new Item.Properties()));
        helper.register("burnt_potato_cuts", new Item(new Item.Properties()));
        helper.register("burnt_potato_slice", new Item(new Item.Properties()));
        helper.register("burnt_rabbit_leg", new Item(new Item.Properties()));
        helper.register("burnt_rabbit_slice", new Item(new Item.Properties()));
        helper.register("burnt_salmon_fillet", new Item(new Item.Properties()));
        helper.register("burnt_slice", new Item(new Item.Properties()));
        helper.register("burnt_spaghetti_pasta", new Item(new Item.Properties()));
        helper.register("burnt_toast", new Item(new Item.Properties()));
        helper.register("burnt_tortellini_pasta", new Item(new Item.Properties()));
        helper.register("burnt_rice_cake", new Item(new Item.Properties()));
        helper.register("burnt_tomato_slice", new Item(new Item.Properties()));
        helper.register("chocolate_yogurt", new Item(new Item.Properties().food(FoodList.CHOCOLATE_YOGURT)));
        helper.register("cooked_bacon", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_BACON), DrinkList.COOKED_BACON));
        helper.register("cooked_beef_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_BEEF_SLICE), DrinkList.COOKED_BEEF_SLICE));
        helper.register("cooked_beetroot_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_BEETROOT_SLICE), DrinkList.COOKED_BEETROOT_SLICE));
        helper.register("cooked_bell_pepper_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_BELL_PEPPER_SLICE), DrinkList.COOKED_BELL_PEPPER_SLICE));
        helper.register("cooked_chicken_breast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_CHICKEN_BREAST), DrinkList.COOKED_CHICKEN_BREAST));
        helper.register("cooked_chicken_drumstick", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_CHICKEN_DRUMSTICK), DrinkList.COOKED_CHICKEN_DRUMSTICK));
        helper.register("cooked_diced_beef_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_DICED_BEEF_MEAT), DrinkList.COOKED_DICED_BEEF_MEAT));
        helper.register("cooked_diced_beetroot", new MasteryApplicableItem(new Item.Properties().food(FoodList.COOKED_DICED_BEETROOT)));
        helper.register("cooked_diced_carrot", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_DICED_CARROT), DrinkList.COOKED_DICED_CARROT));
        helper.register("cooked_diced_chicken_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_DICED_CHICKEN_MEAT), DrinkList.COOKED_DICED_CHICKEN_MEAT));
        helper.register("cooked_diced_pork_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_DICED_PORK_MEAT), DrinkList.COOKED_DICED_PORK_MEAT));
        helper.register("cooked_diced_scallion", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_DICED_SCALLION), DrinkList.COOKED_DICED_SCALLION));
        helper.register("cooked_diced_tomato", new MasteryApplicableItem(new Item.Properties().food(FoodList.COOKED_DICED_TOMATO)));
        helper.register("cooked_fish_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_FISH_FILLET), DrinkList.COOKED_FISH_FILLET));
        helper.register("cooked_fries", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_FRIES), DrinkList.COOKED_FRIES));
        helper.register("cooked_garlic_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_GARLIC_SLICE), DrinkList.COOKED_GARLIC_SLICE));
        helper.register("cooked_leek_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_LEEK_SLICE), DrinkList.COOKED_LEEK_SLICE));
        helper.register("cooked_portobello_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_PORTOBELLO_SLICE), DrinkList.COOKED_PORTOBELLO_SLICE));
        helper.register("cooked_rabbit_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_RABBIT_SLICE), DrinkList.COOKED_RABBIT_SLICE));
        helper.register("cooked_salmon_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_SALMON_FILLET), DrinkList.COOKED_SALMON_FILLET));
        helper.register("fried_potato_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.FRIED_POTATO_SLICE), DrinkList.FRIED_POTATO_SLICE));
        helper.register("grilled_beef_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_BEEF_STEAK), DrinkList.GRILLED_BEEF_STEAK));
        helper.register("grilled_carrot_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CARROT_SLICE), DrinkList.GRILLED_CARROT_SLICE));
        helper.register("grilled_chicken_breast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CHICKEN_BREAST), DrinkList.GRILLED_CHICKEN_BREAST));
        helper.register("grilled_chicken_drumstick", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CHICKEN_DRUMSTICK), DrinkList.GRILLED_CHICKEN_DRUMSTICK));
        helper.register("grilled_chicken_wing", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CHICKEN_WING), DrinkList.GRILLED_CHICKEN_WING));
        helper.register("grilled_corn_cob", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CORN_COB), DrinkList.GRILLED_CORN_COB));
        helper.register("grilled_eggplant_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_EGGPLANT_SLICE), DrinkList.GRILLED_EGGPLANT_SLICE));
        helper.register("grilled_fish_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_FISH_FILLET), DrinkList.GRILLED_FISH_FILLET));
        helper.register("grilled_mutton_ribs", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_MUTTON_RIBS), DrinkList.GRILLED_MUTTON_RIBS));
        helper.register("grilled_mutton_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_MUTTON_SLICE), DrinkList.GRILLED_MUTTON_SLICE));
        helper.register("grilled_pineapple_rings", new MasteryApplicableItem(new Item.Properties().food(FoodList.GRILLED_PINEAPPLE_RINGS)));
        helper.register("grilled_pork_ribs", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_PORK_RIBS), DrinkList.GRILLED_PORK_RIBS));
        helper.register("grilled_pork_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_PORK_STEAK), DrinkList.GRILLED_PORK_STEAK));
        helper.register("grilled_salmon_fillet", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_SALMON_FILLET), DrinkList.GRILLED_SALMON_FILLET));
        helper.register("grilled_tomato_slice", new MasteryApplicableItem(new Item.Properties().food(FoodList.GRILLED_TOMATO_SLICE)));
        helper.register("roasted_coffee_beans", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ROASTED_COFFEE_BEANS), DrinkList.ROASTED_COFFEE_BEANS));
        helper.register("roasted_peanuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ROASTED_PEANUTS), DrinkList.ROASTED_PEANUTS));
        helper.register("toast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TOAST), DrinkList.TOAST));
        helper.register("vanilla_milkshake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VANILLA_MILKSHAKE), DrinkList.VANILLA_MILKSHAKE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("vanilla_yogurt", new MasteryApplicableItem(new Item.Properties().food(FoodList.VANILLA_YOGURT)));
        helper.register("yeast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.YEAST), DrinkList.YEAST));
        helper.register("beef_jerky", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BEEF_JERKY), DrinkList.BEEF_JERKY));
        helper.register("boiled_tomato", new MasteryApplicableItem(new Item.Properties().food(FoodList.BOILED_TOMATO)));
        helper.register("bread_crumbs", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BREAD_CRUMBS), DrinkList.BREAD_CRUMBS));
        helper.register("burnt_camembert", new MasteryApplicableItem(new Item.Properties()));
        helper.register("burnt_tomato", new MasteryApplicableItem(new Item.Properties()));
        helper.register("butter", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BUTTER), DrinkList.BUTTER));
        helper.register("camembert", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CAMEMBERT), DrinkList.CAMEMBERT));
        helper.register("camembert_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CAMEMBERT_SLICE), DrinkList.CAMEMBERT_SLICE));
        helper.register("cheese", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHEESE), DrinkList.CHEESE));
        helper.register("cheese_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHEESE_CUTS), DrinkList.CHEESE_CUTS));
        helper.register("cheese_slice", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHEESE_SLICE), DrinkList.CHEESE_SLICE));
        helper.register("chicken_jerky", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHICKEN_JERKY), DrinkList.CHICKEN_JERKY));
        helper.register("cream", new ConsumableItem(new Item.Properties().food(FoodList.CREAM)).returns(() -> Items.BOWL));
        helper.register("cured_beef_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CURRED_BEEF_STEAK), DrinkList.CURRED_BEEF_STEAK));
        helper.register("cured_chicken_breast", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CURRED_CHICKEN_STEAK), DrinkList.CURRED_CHICKEN_STEAK));
        helper.register("cured_pork_steak", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CURRED_PORK_STEAK), DrinkList.CURRED_PORK_STEAK));
        helper.register("grilled_camembert", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRILLED_CAMEMBERT), DrinkList.GRILLED_CAMEMBERT));
        helper.register("milk", new DrinkableConsumableItem(new Item.Properties(), DrinkList.MILK, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("pork_jerky", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PORK_JERKY), DrinkList.PORK_JERKY));
        helper.register("rice_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RICE_DOUGH), DrinkList.RICE_DOUGH));
        helper.register("shredded_cheese", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_CHEESE), DrinkList.SHREDDED_CHEESE));
        helper.register("shredded_garlic", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SHREDDED_GARLIC), DrinkList.SHREDDED_GARLIC));
        helper.register("sweet_rice_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SWEET_RICE_DOUGH), DrinkList.SWEET_RICE_DOUGH));
        helper.register("tomato_sauce", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TOMATO_SAUCE), DrinkList.TOMATO_SAUCE).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("whipped_cream", new ConsumableItem(new Item.Properties().food(FoodList.WHIPPED_CREAM)).returns(() -> Items.BOWL));
        helper.register("baguette", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BAGUETTE), DrinkList.BAGUETTE));
        helper.register("blueberry_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BLUEBERRY_ICE_CREAM), DrinkList.BLUEBERRY_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("burger_bun", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BURGER_BUN), DrinkList.BURGER_BUN));
        helper.register("burnt_baguette", new Item(new Item.Properties()));
        helper.register("burnt_bread", new Item(new Item.Properties()));
        helper.register("burnt_burger_bun", new Item(new Item.Properties()));
        helper.register("burnt_caramel", new Item(new Item.Properties()));
        helper.register("burnt_chocolate_bar", new Item(new Item.Properties()));
        helper.register("burnt_roll", new Item(new Item.Properties()));
        helper.register("burnt_waffle", new Item(new Item.Properties()));
        helper.register("caramel", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CARAMEL), DrinkList.CARAMEL));
        helper.register("caramel_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CARAMEL_ICE_CREAM), DrinkList.CARAMEL_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("cherry_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHERRY_ICE_CREAM), DrinkList.CHERRY_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("chocolate_bar", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHOCOLATE_BAR), DrinkList.CHOCOLATE_BAR));
        helper.register("chocolate_chips", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHOCOLATE_CHIPS), DrinkList.CHOCOLATE_CHIPS));
        helper.register("chocolate_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CHOCOLATE_ICE_CREAM), DrinkList.CHOCOLATE_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("dried_baguette", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_BAGUETTE), DrinkList.DRIED_BAGUETTE));
        helper.register("dried_roll", new DrinkableConsumableItem(new Item.Properties().food(FoodList.DRIED_ROLL), DrinkList.DRIED_ROLL));
        helper.register("grated_chocolate", new DrinkableConsumableItem(new Item.Properties().food(FoodList.GRATED_CHOCOLATE), DrinkList.GRATED_CHOCOLATE));
        helper.register("ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ICE_CREAM), DrinkList.ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("lemon_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.LEMON_ICE_CREAM), DrinkList.LEMON_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("raspberry_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RASPBERRY_ICE_CREAM), DrinkList.RASPBERRY_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("raw_baguette", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_BAGUETTE), DrinkList.RAW_BAGUETTE));
        helper.register("raw_bread", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_BREAD), DrinkList.RAW_BREAD));
        helper.register("raw_burger_bun", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_BURGER_BUN), DrinkList.RAW_BURGER_BUN));
        helper.register("raw_roll", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_ROLL), DrinkList.RAW_ROLL));
        helper.register("raw_waffle", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_WAFFLE), DrinkList.RAW_WAFFLE));
        helper.register("roll", new DrinkableConsumableItem(new Item.Properties().food(FoodList.ROLL), DrinkList.ROLL));
        helper.register("stracciatella_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.STRACCIATELLA_ICE_CREAM), DrinkList.STRACCIATELLA_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("strawberry_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.STRAWBERRY_ICE_CREAM), DrinkList.STRAWBERRY_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("vanilla_ice_cream", new DrinkableConsumableItem(new Item.Properties().food(FoodList.VANILLA_ICE_CREAM), DrinkList.VANILLA_ICE_CREAM).returns(() -> Items.BOWL));
        helper.register("waffle", new DrinkableConsumableItem(new Item.Properties().food(FoodList.WAFFLE), DrinkList.WAFFLE));
        helper.register("berry_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BERRY_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("black_coffee", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BLACK_COFFEE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("boiled_egg", new Item(new Item.Properties()));
        helper.register("boiled_egg_cuts", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_EGG_CUTS), DrinkList.BOILED_EGG_CUTS));
        helper.register("burnt_corn_bread", new Item(new Item.Properties()));
        helper.register("burnt_egg", new Item(new Item.Properties()));
        helper.register("burnt_nachos", new Item(new Item.Properties()));
        helper.register("burnt_pita", new Item(new Item.Properties()));
        helper.register("burnt_tortilla", new Item(new Item.Properties()));
        helper.register("cappuccino", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CAPPUCCINO, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("citrus_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.CITRUS_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("corn_bread", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CORN_BREAD), DrinkList.CORN_BREAD));
        helper.register("dandelion_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.DANDELION_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("espresso", new DrinkableConsumableItem(new Item.Properties(), DrinkList.ESPRESSO, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("fruit_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.FRUIT_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("ginger_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.GINGER_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("honey_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.HONEY_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("hot_caramel_chocolate", new DrinkableConsumableItem(new Item.Properties(), DrinkList.HOT_CARAMEL_CHOCOLATE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("hot_chilli_chocolate", new DrinkableConsumableItem(new Item.Properties(), DrinkList.HOT_CHILLI_CHOCOLATE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("hot_chocolate", new DrinkableConsumableItem(new Item.Properties(), DrinkList.HOT_CHOCOLATE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("ice_coffee", new DrinkableConsumableItem(new Item.Properties(), DrinkList.ICE_COFFEE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("latte", new DrinkableConsumableItem(new Item.Properties(), DrinkList.LATTE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("milk_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.MILK_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("mug", new Item(new Item.Properties()));
        helper.register("mulled_wine", new DrinkableConsumableItem(new Item.Properties(), DrinkList.MULLED_WINE, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("nachos", new DrinkableConsumableItem(new Item.Properties().food(FoodList.NACHOS), DrinkList.NACHOS));
        helper.register("pita", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PITA), DrinkList.PITA));
        helper.register("raw_corn_bread", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CORN_BREAD), DrinkList.RAW_CORN_BREAD));
        helper.register("raw_nachos", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_NACHOS), DrinkList.RAW_NACHOS));
        helper.register("raw_pita", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PITA), DrinkList.RAW_PITA));
        helper.register("raw_tortilla", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_TORTILLA), DrinkList.RAW_TORTILLA));
        helper.register("tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.MUG));
        helper.register("tortilla", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TORTILLA), DrinkList.TORTILLA));
        helper.register("unfinished_mug", new Item(new Item.Properties()));
        helper.register("avocado_pesto", new DrinkableConsumableItem(new Item.Properties().food(FoodList.AVOCADO_PESTO), DrinkList.AVOCADO_PESTO).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("boiled_beans", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_BEANS), DrinkList.BOILED_BEANS));
        helper.register("bottle_of_water", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BOTTLE_OF_WATER, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("burnt_beans", new Item(new Item.Properties()));
        helper.register("burnt_onion", new Item(new Item.Properties()));
        helper.register("burnt_soy_meat", new Item(new Item.Properties()));
        helper.register("burnt_spinach", new DumpItem(new Item.Properties()).returns(() -> Items.BOWL));
        helper.register("burnt_hot_chocolate", new DumpItem(new Item.Properties()).returns(() -> BlockyChefItems.MUG));
        helper.register("burnt_vegetable_stock", new DumpItem(new Item.Properties()).returns(() -> Items.BOWL));
        helper.register("burnt_meat_stock", new DumpItem(new Item.Properties()).returns(() -> Items.BOWL));
        helper.register("cooked_onion", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_ONION), DrinkList.COOKED_ONION));
        helper.register("cooked_soy_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_SOY_MEAT), DrinkList.COOKED_SOY_MEAT));
        helper.register("ice_tea", new DrinkableConsumableItem(new Item.Properties(), DrinkList.ICE_TEA, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("pesto", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PESTO), DrinkList.PESTO).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("raw_soy_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_SOY_MEAT), DrinkList.RAW_SOY_MEAT));
        helper.register("rice_dumpling_wrapper", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RICE_DUMPLING_WRAPPER), DrinkList.RICE_DUMPLING_WRAPPER));
        helper.register("rice_paper", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RICE_PAPER), DrinkList.RICE_PAPER));
        helper.register("rock_salt", new Item(new Item.Properties()));
        helper.register("soy_flour", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SOY_FLOUR), DrinkList.SOY_FLOUR));
        helper.register("spinach", new DrinkableConsumableItem(new Item.Properties().food(FoodList.SPINACH), DrinkList.SPINACH).returns(() -> Items.BOWL));
        helper.register("tofu", new DrinkableConsumableItem(new Item.Properties().food(FoodList.TOFU), DrinkList.TOFU));
        helper.register("wheat_flour", new DrinkableConsumableItem(new Item.Properties().food(FoodList.WHEAT_FLOUR), DrinkList.WHEAT_FLOUR));
        helper.register("boiled_cheese_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_CHEESE_TORTELLINI), DrinkList.BOILED_CHEESE_TORTELLINI));
        helper.register("boiled_mushroom_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_MUSHROOM_TORTELLINI), DrinkList.BOILED_MUSHROOM_TORTELLINI));
        helper.register("boiled_pork_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_PORK_TORTELLINI), DrinkList.BOILED_PORK_TORTELLINI));
        helper.register("boiled_spinach_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.BOILED_SPINACH_TORTELLINI), DrinkList.BOILED_SPINACH_TORTELLINI));
        helper.register("cooked_grounded_beef_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_GROUNDED_BEEF_MEAT), DrinkList.COOKED_GROUNDED_BEEF_MEAT));
        helper.register("cooked_grounded_pork_meat", new DrinkableConsumableItem(new Item.Properties().food(FoodList.COOKED_GROUNDED_PORK_MEAT), DrinkList.COOKED_GROUNDED_PORK_MEAT));
        helper.register("cupcake_base", new DrinkableConsumableItem(new Item.Properties().food(FoodList.CUPCAKE_BASE), DrinkList.CUPCAKE_BASE));
        helper.register("mashed_potatoes", new DrinkableConsumableItem(new Item.Properties().food(FoodList.MASHED_POTATOES), DrinkList.MASHED_POTATOES).returns(() -> Items.BOWL));
        helper.register("pie_crust", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PIE_CRUST), DrinkList.PIE_CRUST));
        helper.register("pizza_dough", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PIZZA_DOUGH), DrinkList.PIZZA_DOUGH));
        helper.register("raw_cheese_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_CHEESE_TORTELLINI), DrinkList.RAW_CHEESE_TORTELLINI));
        helper.register("raw_mushroom_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_MUSHROOM_TORTELLINI), DrinkList.RAW_MUSHROOM_TORTELLINI));
        helper.register("raw_pork_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_PORK_TORTELLINI), DrinkList.RAW_PORK_TORTELLINI));
        helper.register("raw_rice_cake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_RICE_CAKE), DrinkList.RAW_RICE_CAKE));
        helper.register("raw_spinach_tortellini", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RAW_SPINACH_TORTELLINI), DrinkList.RAW_SPINACH_TORTELLINI));
        helper.register("rice_cake", new DrinkableConsumableItem(new Item.Properties().food(FoodList.RICE_CAKE), DrinkList.RICE_CAKE));
        helper.register("burnt_marmalade", new DumpItem(new Item.Properties()).returns(() -> BlockyChefItems.EMPTY_JAR));
        helper.register("burnt_cheese_tortellini", new Item(new Item.Properties()));
        helper.register("burnt_pork_tortellini", new Item(new Item.Properties()));
        helper.register("burnt_mushroom_tortellini", new Item(new Item.Properties()));
        helper.register("burnt_spinach_tortellini", new Item(new Item.Properties()));
        helper.register("burnt_deluxe_skewer", new Item(new Item.Properties()));
        helper.register("burnt_chicken_skewer", new Item(new Item.Properties()));
        helper.register("burnt_pork_skewer", new Item(new Item.Properties()));
        helper.register("burnt_veggie_skewer", new Item(new Item.Properties()));
        helper.register("peeled_onion", new DrinkableConsumableItem(new Item.Properties().food(FoodList.PEELED_ONION), DrinkList.PEELED_ONION));
        helper.register("coconut_flakes", new MasteryApplicableItem(new Item.Properties().food(FoodList.COCONUT_FLAKES)));
        helper.register("sweet_berry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.SWEET_BERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_GLASS));
        helper.register("frappe_coffee", new DrinkableConsumableItem(new Item.Properties().food(FoodList.FRAPPE_COFFEE), DrinkList.FRAPPE_COFFEE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_LARGE_GLASS));
        helper.register("dried_tea_leaf", new Item(new Item.Properties()));
        helper.register("bubbly_water", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_WATER, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_apple_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_APPLE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_blueberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_BLUEBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_cherry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_CHERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_grape_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_GRAPE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_lemonade", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_LEMONADE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_lime_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_LIME_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_melon_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_MELON_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_orange_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_ORANGE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_peach_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_PEACH_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_pear_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_PEAR_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_pineapple_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_PINEAPPLE_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_plum_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_PLUM_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_raspberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_RASPBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_sweet_berry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_SWEET_BERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("bubbly_strawberry_juice", new DrinkableConsumableItem(new Item.Properties(), DrinkList.BUBBLY_STRAWBERRY_JUICE, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));


    }
}
