package tnt.blockychef.common.registry;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.UseAnim;
import net.minecraftforge.registries.RegisterEvent;
import tnt.blockychef.common.food.DrinkList;
import tnt.blockychef.common.food.FoodList;
import tnt.blockychef.common.init.BlockyChefBlocks;
import tnt.blockychef.common.init.BlockyChefItems;
import tnt.blockychef.common.item.ConsumableItem;
import tnt.blockychef.common.item.CropSeedsItem;
import tnt.blockychef.common.item.EdibleCropSeedItem;

public final class ItemRegistry {

    public static void register(RegisterEvent.RegisterHelper<Item> helper) {
        helper.register("tomato", new EdibleCropSeedItem(BlockyChefBlocks.TOMATO_CROPS, new Item.Properties().food(FoodList.TOMATO), DrinkList.TOMATO));
        helper.register("cucumber", new CropSeedsItem(BlockyChefBlocks.CUCUMBER_CROPS, new Item.Properties().food(FoodList.CUCUMBER)));
        helper.register("bell_pepper", new EdibleCropSeedItem(BlockyChefBlocks.BELL_PEPPER_CROPS, new Item.Properties().food(FoodList.BELL_PEPPER), DrinkList.BELL_PEPPER));
        helper.register("black_pepper_cluster", new EdibleCropSeedItem(BlockyChefBlocks.BLACK_PEPPER_CROPS, new Item.Properties().food(FoodList.BLACK_PEPPER), DrinkList.BLACK_PEPPER));
        helper.register("blueberry", new CropSeedsItem(BlockyChefBlocks.BLUEBERRY_CROPS, new Item.Properties().food(FoodList.BLUEBERRY)));
        helper.register("broccoli", new EdibleCropSeedItem(BlockyChefBlocks.BROCCOLI_CROPS, new Item.Properties().food(FoodList.BROCCOLI), DrinkList.BROCCOLI));
        helper.register("cabbage", new EdibleCropSeedItem(BlockyChefBlocks.CABBAGE_CROPS, new Item.Properties().food(FoodList.CABBAGE), DrinkList.CABBAGE));
        helper.register("chilli_pepper", new EdibleCropSeedItem(BlockyChefBlocks.CHILLI_PEPPER_CROPS, new Item.Properties().food(FoodList.CHILLI_PEPPER), DrinkList.CHILLI_PEPPER));
        helper.register("corn_cob", new EdibleCropSeedItem(BlockyChefBlocks.CORN_CROPS, new Item.Properties().food(FoodList.CORN_COB), DrinkList.CORN_COB));
        helper.register("garlic", new EdibleCropSeedItem(BlockyChefBlocks.GARLIC_CROPS, new Item.Properties().food(FoodList.GARLIC), DrinkList.GARLIC));
        helper.register("leek", new EdibleCropSeedItem(BlockyChefBlocks.LEEK_CROPS, new Item.Properties().food(FoodList.LEEK), DrinkList.LEEK));
        helper.register("lettuce", new EdibleCropSeedItem(BlockyChefBlocks.LETTUCE_CROPS, new Item.Properties().food(FoodList.LETTUCE), DrinkList.LETTUCE));
        helper.register("onion", new EdibleCropSeedItem(BlockyChefBlocks.ONION_CROPS, new Item.Properties().food(FoodList.ONION), DrinkList.ONION));
        helper.register("parsley", new EdibleCropSeedItem(BlockyChefBlocks.PARSLEY_CROPS, new Item.Properties().food(FoodList.PARSLEY), DrinkList.PARSLEY));
        helper.register("raspberry", new CropSeedsItem(BlockyChefBlocks.RASPBERRY_CROPS, new Item.Properties().food(FoodList.RASPBERRY)));
        helper.register("spring_onion", new EdibleCropSeedItem(BlockyChefBlocks.SPRING_ONION_CROPS, new Item.Properties().food(FoodList.SPRING_ONION), DrinkList.SPRING_ONION));
        helper.register("strawberry", new CropSeedsItem(BlockyChefBlocks.STRAWBERRY_CROPS, new Item.Properties().food(FoodList.STRAWBERRY)));
        helper.register("turmeric", new EdibleCropSeedItem(BlockyChefBlocks.TURMERIC_CROPS, new Item.Properties().food(FoodList.TURMERIC), DrinkList.TURMERIC));
        helper.register("pineapple", new EdibleCropSeedItem(BlockyChefBlocks.PINEAPPLE_CROPS, new Item.Properties().food(FoodList.PINEAPPLE), DrinkList.PINEAPPLE));
        helper.register("portobello_mushroom", new EdibleCropSeedItem(BlockyChefBlocks.PORTOBELLO_CROPS, new Item.Properties().food(FoodList.PORTOBELLO), DrinkList.PORTOBELLO));
        helper.register("bean_pod", new EdibleCropSeedItem(BlockyChefBlocks.BEANS_CROPS, new Item.Properties().food(FoodList.BEANS_POD), DrinkList.BEANS_POD));
        helper.register("peanut", new EdibleCropSeedItem(BlockyChefBlocks.PEANUTS_CROPS, new Item.Properties().food(FoodList.PEANUT), DrinkList.PEANUT));
        helper.register("pea_pod", new EdibleCropSeedItem(BlockyChefBlocks.PEAS_CROPS, new Item.Properties().food(FoodList.PEA_POD), DrinkList.PEA_POD));
        helper.register("soybean_pod", new EdibleCropSeedItem(BlockyChefBlocks.SOYBEANS_CROPS, new Item.Properties().food(FoodList.SOYBEANS), DrinkList.SOYBEANS));
        helper.register("basil", new EdibleCropSeedItem(BlockyChefBlocks.BASIL_CROPS, new Item.Properties().food(FoodList.BASIL), DrinkList.BASIL));
        helper.register("ginger_root", new EdibleCropSeedItem(BlockyChefBlocks.GINGER_CROPS, new Item.Properties().food(FoodList.GINGER), DrinkList.GINGER));
        helper.register("tea_leaf", new EdibleCropSeedItem(BlockyChefBlocks.TEA_CROPS, new Item.Properties().food(FoodList.TEA), DrinkList.TEA));
        helper.register("grapes", new EdibleCropSeedItem(BlockyChefBlocks.GRAPES_CROPS, new Item.Properties().food(FoodList.GRAPES), DrinkList.GRAPES));
        helper.register("rice_crop", new EdibleCropSeedItem(BlockyChefBlocks.RICE_CROPS, new Item.Properties().food(FoodList.RICE), DrinkList.RICE));
        helper.register("oat_crop", new EdibleCropSeedItem(BlockyChefBlocks.OAT_CROPS, new Item.Properties().food(FoodList.OAT), DrinkList.OAT));
        helper.register("mustard_pods", new EdibleCropSeedItem(BlockyChefBlocks.MUSTARD_CROPS, new Item.Properties().food(FoodList.MUSTARD_PODS), DrinkList.MUSTARD_PODS));
        helper.register("coffee_beans_cluster", new EdibleCropSeedItem(BlockyChefBlocks.COFFEE_CROPS, new Item.Properties().food(FoodList.COFFEE), DrinkList.COFFEE));
        helper.register("eggplant", new EdibleCropSeedItem(BlockyChefBlocks.EGGPLANT_CROPS, new Item.Properties().food(FoodList.EGGPLANT), DrinkList.EGGPLANT));
        helper.register("spinach_leaf", new EdibleCropSeedItem(BlockyChefBlocks.SPINACH_CROPS, new Item.Properties().food(FoodList.SPINACH_LEAF), DrinkList.SPINACH_LEAF));
        helper.register("almond", new ConsumableItem(new Item.Properties().food(FoodList.ALMOND), DrinkList.ALMOND));
        helper.register("avocado", new ConsumableItem(new Item.Properties().food(FoodList.AVOCADO), DrinkList.AVOCADO));
        helper.register("banana", new ConsumableItem(new Item.Properties().food(FoodList.BANANA), DrinkList.BANANA));
        helper.register("black_olives", new ConsumableItem(new Item.Properties().food(FoodList.BLACK_OLIVES), DrinkList.BLACK_OLIVES));
        helper.register("cherry", new Item(new Item.Properties().food(FoodList.CHERRY)));
        helper.register("coconut", new Item(new Item.Properties()));
        helper.register("green_olives", new ConsumableItem(new Item.Properties().food(FoodList.GREEN_OLIVES), DrinkList.GREEN_OLIVES));
        helper.register("hazelnut", new ConsumableItem(new Item.Properties().food(FoodList.HAZELNUT), DrinkList.HAZELNUT));
        helper.register("lemon", new Item(new Item.Properties().food(FoodList.LEMON)));
        helper.register("lime", new Item(new Item.Properties().food(FoodList.LIME)));
        helper.register("orange", new ConsumableItem(new Item.Properties().food(FoodList.ORANGE), DrinkList.ORANGE));
        helper.register("peach", new Item(new Item.Properties().food(FoodList.PEACH)));
        helper.register("pear", new Item(new Item.Properties().food(FoodList.PEAR)));
        helper.register("plum", new Item(new Item.Properties().food(FoodList.PLUM)));
        helper.register("cinnamon_bark", new Item(new Item.Properties()));
        helper.register("vanilla_pods", new ConsumableItem(new Item.Properties().food(FoodList.VANILLA_PODS), DrinkList.VANILLA_PODS));
        helper.register("walnut", new ConsumableItem(new Item.Properties().food(FoodList.WALNUT), DrinkList.WALNUT));

        helper.register("shrimp", new Item(new Item.Properties().food(FoodList.SHRIMP)));
        helper.register("raw_shrimp", new Item(new Item.Properties().food(FoodList.RAW_SHRIMP)));
        helper.register("fried_shrimp", new ConsumableItem(new Item.Properties().food(FoodList.FRIED_SHRIMP), DrinkList.FRIED_SHRIMP));
        helper.register("burnt_shrimp", new Item(new Item.Properties()));

        helper.register("apple_extract", new ConsumableItem(new Item.Properties(), DrinkList.APPLE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("apple_half", new Item(new Item.Properties().food(FoodList.APPLE_HALF)));
        helper.register("apple_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.APPLE_MARMALADE), DrinkList.APPLE_MARMALADE));
        helper.register("apple_slice", new Item(new Item.Properties().food(FoodList.APPLE_SLICE)));
        helper.register("avocado_slice", new ConsumableItem(new Item.Properties().food(FoodList.AVOCADO_SLICE), DrinkList.AVOCADO_SLICE));
        helper.register("banana_slice", new ConsumableItem(new Item.Properties().food(FoodList.BANANA_SLICE), DrinkList.BANANA_SLICE));
        helper.register("bbq_sauce", new ConsumableItem(new Item.Properties().food(FoodList.BBQ_SAUCE), DrinkList.BBQ_SAUCE));
        helper.register("beans", new ConsumableItem(new Item.Properties().food(FoodList.BEANS), DrinkList.BEANS));
        helper.register("beef_burger_patty", new ConsumableItem(new Item.Properties().food(FoodList.BEEF_BURGER_PATTY), DrinkList.BEEF_BURGER_PATTY));
        helper.register("beef_slice", new Item(new Item.Properties().food(FoodList.BEEF_SLICE)));
        helper.register("beetroot_slice", new Item(new Item.Properties().food(FoodList.BEETROOT_SLICE)));
        helper.register("bell_pepper_slice", new ConsumableItem(new Item.Properties().food(FoodList.BELL_PEPPER_SLICE), DrinkList.BELL_PEPPER_SLICE));
        helper.register("black_olive_slice", new ConsumableItem(new Item.Properties().food(FoodList.BLACK_OLIVE_SLICE), DrinkList.BLACK_OLIVE_SLICE));
        helper.register("blueberry_extract", new ConsumableItem(new Item.Properties(), DrinkList.BLUEBERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("blueberry_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.BLUEBERRY_MARMALADE), DrinkList.BLUEBERRY_MARMALADE));
        helper.register("boiled_rice", new ConsumableItem(new Item.Properties().food(FoodList.BOILED_RICE), DrinkList.BOILED_RICE));
        helper.register("bread_slice", new ConsumableItem(new Item.Properties().food(FoodList.BREAD_SLICE), DrinkList.BREAD_SLICE));
        helper.register("broccoli_cuts", new ConsumableItem(new Item.Properties().food(FoodList.BROCCOLI_CUTS), DrinkList.BROCCOLI_CUTS));
        helper.register("burnt_beef_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_chicken_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_pork_burger_patty", new Item(new Item.Properties()));
        helper.register("burnt_rice", new Item(new Item.Properties()));
        helper.register("cabbage_leaf", new ConsumableItem(new Item.Properties().food(FoodList.CABBAGE_LEAF), DrinkList.CABBAGE_LEAF));
        helper.register("carrot_extract", new ConsumableItem(new Item.Properties(), DrinkList.CARROT_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("carrot_slice", new Item(new Item.Properties().food(FoodList.CARROT_SLICE)));
        helper.register("cherry_extract", new ConsumableItem(new Item.Properties(), DrinkList.CHERRY_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));;
        helper.register("cherry_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.CHERRY_MARMALADE), DrinkList.CHERRY_MARMALADE));
        helper.register("chicken_burger_patty", new ConsumableItem(new Item.Properties().food(FoodList.CHICKEN_BURGER_PATTY), DrinkList.CHICKEN_BURGER_PATTY));
        helper.register("chilli_powder", new ConsumableItem(new Item.Properties().food(FoodList.CHILLI_POWDER), DrinkList.CHILLI_POWDER));
        helper.register("cinnamon_powder", new ConsumableItem(new Item.Properties().food(FoodList.CINNAMON_POWDER), DrinkList.CINNAMON_POWDER));
        helper.register("cocoa_powder", new ConsumableItem(new Item.Properties().food(FoodList.COCOA_POWDER), DrinkList.COCOA_POWDER));
        helper.register("cocoa_spread", new ConsumableItem(new Item.Properties().food(FoodList.COCOA_SPREAD), DrinkList.COCOA_SPREAD));
        helper.register("coconut_half", new Item(new Item.Properties().food(FoodList.COCONUT_HALF)));
        helper.register("coconut_milk", new ConsumableItem(new Item.Properties(), DrinkList.COCONUT_MILK, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("coffee_beans", new ConsumableItem(new Item.Properties().food(FoodList.COFFEE_BEANS), DrinkList.COFFEE_BEANS));
        helper.register("coffee_powder", new ConsumableItem(new Item.Properties().food(FoodList.COFFEE_POWDER), DrinkList.COFFEE_POWDER));
        helper.register("corn", new ConsumableItem(new Item.Properties().food(FoodList.CORN), DrinkList.CORN));
        helper.register("corn_meal", new ConsumableItem(new Item.Properties().food(FoodList.CORN_MEAL), DrinkList.CORN_MEAL));
        helper.register("cracked_egg", new Item(new Item.Properties().food(FoodList.CRACKED_EGG)));
        helper.register("cucumber_slice", new Item(new Item.Properties().food(FoodList.CUCUMBER_SLICE)));
        helper.register("curry_powder", new ConsumableItem(new Item.Properties().food(FoodList.CURRY_POWDER), DrinkList.CURRY_POWDER));
        helper.register("diced_beef_meat", new Item(new Item.Properties().food(FoodList.DICED_BEEF_MEAT)));
        helper.register("diced_beetroot", new Item(new Item.Properties().food(FoodList.DICED_BEETROOT)));
        helper.register("diced_carrot", new Item(new Item.Properties().food(FoodList.DICED_CARROT)));
        helper.register("diced_chicken_meat", new Item(new Item.Properties().food(FoodList.DICED_CHICKEN_MEAT)));
        helper.register("diced_chilli_pepper", new ConsumableItem(new Item.Properties().food(FoodList.DICED_CHILLI_PEPPER), DrinkList.DICED_CHILLI_PEPPER));
        helper.register("diced_onion", new ConsumableItem(new Item.Properties().food(FoodList.DICED_ONION), DrinkList.DICED_ONION));
        helper.register("diced_pork_meat", new Item(new Item.Properties().food(FoodList.DICED_PORK_MEAT)));
        helper.register("diced_scallion", new ConsumableItem(new Item.Properties().food(FoodList.DICED_SCALLION), DrinkList.DICED_SCALLION));
        helper.register("diced_tomato", new ConsumableItem(new Item.Properties().food(FoodList.DICED_TOMATO), DrinkList.DICED_TOMATO));
        helper.register("dried_basil", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_BASIL), DrinkList.DRIED_BASIL));
        helper.register("dried_black_pepper_cluster", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_BLACK_PEPPER_CLUSTER), DrinkList.DRIED_BLACK_PEPPER_CLUSTER));
        helper.register("dried_bread", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_BREAD), DrinkList.DRIED_BREAD));
        helper.register("dried_chilli_pepper", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_CHILLI_PEPPER), DrinkList.DRIED_CHILLI_PEPPER));
        helper.register("dried_cinnamon_bark", new Item(new Item.Properties()));
        helper.register("dried_corn", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_CORN), DrinkList.DRIED_CORN));
        helper.register("dried_corn_cob", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_CORN_COB), DrinkList.DRIED_CORN_COB));
        helper.register("dried_mustard_pods", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_MUSTARD_PODS), DrinkList.DRIED_MUSTARD_PODS));
        helper.register("dried_turmeric_slice", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_TURMERIC_SLICE), DrinkList.DRIED_TURMERIC_SLICE));
        helper.register("dried_vanilla_pods", new ConsumableItem(new Item.Properties().food(FoodList.DRIED_VANILLA_PODS), DrinkList.DRIED_VANILLA_PODS));
        helper.register("eggplant_slice", new ConsumableItem(new Item.Properties().food(FoodList.EGGPLANT_SLICE), DrinkList.EGGPLANT_SLICE));
        helper.register("egg_yolk", new Item(new Item.Properties().food(FoodList.EGG_YOLK)));
        helper.register("empty_bottle", new Item(new Item.Properties()));
        helper.register("empty_jar", new Item(new Item.Properties()));
        helper.register("fried_egg", new ConsumableItem(new Item.Properties().food(FoodList.FRIED_EGG), DrinkList.FRIED_EGG));
        helper.register("garlic_clove", new ConsumableItem(new Item.Properties().food(FoodList.GARLIC_CLOVE), DrinkList.GARLIC_CLOVE));
        helper.register("garlic_slice", new ConsumableItem(new Item.Properties().food(FoodList.GARLIC_SLICE), DrinkList.GARLIC_SLICE));
        helper.register("ginger_slice", new ConsumableItem(new Item.Properties().food(FoodList.GINGER_SLICE), DrinkList.GINGER_SLICE));
        helper.register("grape_extract", new ConsumableItem(new Item.Properties(), DrinkList.GRAPE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("green_olive_slice", new ConsumableItem(new Item.Properties().food(FoodList.GREEN_OLIVE_SLICE), DrinkList.GREEN_OLIVE_SLICE));
        helper.register("grilled_beef_burger_patty", new ConsumableItem(new Item.Properties().food(FoodList.GRILLED_BEEF_BURGER_PATTY), DrinkList.GRILLED_BEEF_BURGER_PATTY));
        helper.register("grilled_chicken_burger_patty", new ConsumableItem(new Item.Properties().food(FoodList.GRILLED_CHICKEN_BURGER_PATTY), DrinkList.GRILLED_CHICKEN_BURGER_PATTY));
        helper.register("grilled_pork_burger_patty", new ConsumableItem(new Item.Properties().food(FoodList.GRILLED_PORK_BURGER_PATTY), DrinkList.GRILLED_PORK_BURGER_PATTY));
        helper.register("grounded_almond", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_ALMOND), DrinkList.GROUNDED_ALMOND));
        helper.register("grounded_basil", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_BASIL), DrinkList.GROUNDED_BASIL));
        helper.register("grounded_beef_meat", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_BEEF_MEAT), DrinkList.GROUNDED_BEEF_MEAT));
        helper.register("grounded_chicken_meat", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_CHICKEN_MEAT), DrinkList.GROUNDED_CHICKEN_MEAT));
        helper.register("grounded_hazelnuts", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_HAZELNUTS), DrinkList.GROUNDED_HAZELNUTS));
        helper.register("grounded_pork_meat", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_PORK_MEAT), DrinkList.GROUNDED_PORK_MEAT));
        helper.register("grounded_walnuts", new ConsumableItem(new Item.Properties().food(FoodList.GROUNDED_WALNUTS), DrinkList.GROUNDED_WALNUTS));
        helper.register("ham_slice", new ConsumableItem(new Item.Properties().food(FoodList.HAM_SLICE), DrinkList.HAM_SLICE));
        helper.register("hazelnuts", new ConsumableItem(new Item.Properties().food(FoodList.HAZELNUTS), DrinkList.HAZELNUTS));
        helper.register("hollowed_bell_pepper", new ConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_BELL_PEPPER), DrinkList.HOLLOWED_BELL_PEPPER));
        helper.register("hollowed_eggplant", new ConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_EGGPLANT), DrinkList.HOLLOWED_EGGPLANT));
        helper.register("hollowed_portobello", new ConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_PORTOBELLO), DrinkList.HOLLOWED_PORTOBELLO));
        helper.register("hollowed_potato", new ConsumableItem(new Item.Properties().food(FoodList.HOLLOWED_POTATO), DrinkList.HOLLOWED_POTATO));
        helper.register("ketchup", new ConsumableItem(new Item.Properties().food(FoodList.KETCHUP), DrinkList.KETCHUP));
        helper.register("leek_slice", new ConsumableItem(new Item.Properties().food(FoodList.LEEK_SLICE), DrinkList.LEEK_SLICE));
        helper.register("lemon_extract", new ConsumableItem(new Item.Properties(), DrinkList.LEMON_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("lemon_half", new Item(new Item.Properties().food(FoodList.LEMON_HALF)));
        helper.register("lemon_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.LEMON_MARMALADE), DrinkList.LEMON_MARMALADE));
        helper.register("lemon_slice", new Item(new Item.Properties().food(FoodList.LEMON_SLICE)));
        helper.register("lettuce_leaf", new ConsumableItem(new Item.Properties().food(FoodList.LETTUCE_LEAF), DrinkList.LETTUCE_LEAF));
        helper.register("lime_extract", new ConsumableItem(new Item.Properties(), DrinkList.LIME_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("lime_half", new Item(new Item.Properties().food(FoodList.LIME_HALF)));
        helper.register("lime_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.LIME_MARMALADE), DrinkList.LIME_MARMALADE));
        helper.register("lime_slice", new Item(new Item.Properties().food(FoodList.LIME_SLICE)));
        helper.register("mayo", new ConsumableItem(new Item.Properties().food(FoodList.MAYO), DrinkList.MAYO));
        helper.register("melon_extract", new ConsumableItem(new Item.Properties(), DrinkList.MELON_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("mustard", new ConsumableItem(new Item.Properties().food(FoodList.MUSTARD), DrinkList.MUSTARD));
        helper.register("oat_meal", new ConsumableItem(new Item.Properties().food(FoodList.OAT_MEAL), DrinkList.OAT_MEAL));
        helper.register("oil", new ConsumableItem(new Item.Properties(), DrinkList.OIL, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("olive_oil", new ConsumableItem(new Item.Properties(), DrinkList.OLIVE_OIL, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("onion_slice", new ConsumableItem(new Item.Properties().food(FoodList.ONION_SLICE), DrinkList.ONION_SLICE));
        helper.register("orange_extract", new ConsumableItem(new Item.Properties(), DrinkList.ORANGE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("orange_half", new ConsumableItem(new Item.Properties().food(FoodList.ORANGE_HALF), DrinkList.ORANGE_HALF));
        helper.register("orange_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.ORANGE_MARMALADE), DrinkList.ORANGE_MARMALADE));
        helper.register("orange_slice", new ConsumableItem(new Item.Properties().food(FoodList.ORANGE_SLICE), DrinkList.ORANGE_SLICE));
        helper.register("parsley_slice", new ConsumableItem(new Item.Properties().food(FoodList.PARSLEY_SLICE), DrinkList.PARSLEY_SLICE));
        helper.register("parsley_stem", new ConsumableItem(new Item.Properties().food(FoodList.PARSLEY_STEM), DrinkList.PARSLEY_STEM));
        helper.register("peach_extract", new ConsumableItem(new Item.Properties(), DrinkList.PEACH_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("peach_half", new Item(new Item.Properties().food(FoodList.PEACH_HALF)));
        helper.register("peach_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.PEACH_MARMALADE), DrinkList.PEACH_MARMALADE));
        helper.register("peach_slice", new Item(new Item.Properties().food(FoodList.PEACH_SLICE)));
        helper.register("peanuts", new ConsumableItem(new Item.Properties().food(FoodList.PEANUTS), DrinkList.PEANUTS));
        helper.register("peanut_butter", new ConsumableItem(new Item.Properties().food(FoodList.PEANUT_BUTTER), DrinkList.PEANUT_BUTTER));
        helper.register("pear_extract", new ConsumableItem(new Item.Properties(), DrinkList.PEAR_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("pear_half", new Item(new Item.Properties().food(FoodList.PEAR_HALF)));
        helper.register("pear_slice", new Item(new Item.Properties().food(FoodList.PEAR_SLICE)));
        helper.register("peas", new ConsumableItem(new Item.Properties().food(FoodList.PEAS), DrinkList.PEAS));
        helper.register("peeled_banana", new ConsumableItem(new Item.Properties().food(FoodList.PEELED_BANANA), DrinkList.PEELED_BANANA));
        helper.register("pepper_powder", new ConsumableItem(new Item.Properties().food(FoodList.PEPPER_POWDER), DrinkList.PEPPER_POWDER));
        helper.register("picked_cherry", new Item(new Item.Properties().food(FoodList.PICKED_CHERRY)));
        helper.register("pineapple_cuts", new ConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_CUTS), DrinkList.PINEAPPLE_CUTS));
        helper.register("pineapple_extract", new ConsumableItem(new Item.Properties(), DrinkList.PINEAPPLE_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("pineapple_half", new ConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_HALF), DrinkList.PINEAPPLE_HALF));
        helper.register("pineapple_rings", new ConsumableItem(new Item.Properties().food(FoodList.PINEAPPLE_RINGS), DrinkList.PINEAPPLE_RINGS));
        helper.register("plum_extract", new ConsumableItem(new Item.Properties(), DrinkList.PLUM_EXTRACT, UseAnim.DRINK).returns(() -> BlockyChefItems.EMPTY_BOTTLE));
        helper.register("plum_half", new Item(new Item.Properties().food(FoodList.PLUM_HALF)));
        helper.register("plum_marmalade", new ConsumableItem(new Item.Properties().food(FoodList.PLUM_MARMALADE), DrinkList.PLUM_MARMALADE));
        helper.register("plum_slice", new Item(new Item.Properties().food(FoodList.PLUM_SLICE)));
        helper.register("pork_burger_patty", new Item(new Item.Properties()));
        helper.register("portobello_slice", new Item(new Item.Properties()));
        helper.register("potato_cuts", new Item(new Item.Properties()));
        helper.register("potato_slice", new Item(new Item.Properties()));
        helper.register("raspberry_extract", new Item(new Item.Properties()));
        helper.register("raspberry_marmalade", new Item(new Item.Properties()));
        helper.register("raw_bacon", new Item(new Item.Properties()));
        helper.register("raw_beef_steak", new Item(new Item.Properties()));
        helper.register("raw_chicken_breast", new Item(new Item.Properties()));
        helper.register("raw_chicken_drumstick", new Item(new Item.Properties()));
        helper.register("raw_chicken_wing", new Item(new Item.Properties()));
        helper.register("raw_corn_cob", new Item(new Item.Properties()));
        helper.register("raw_fish_fillet", new Item(new Item.Properties()));
        helper.register("raw_mutton_ribs", new Item(new Item.Properties()));
        helper.register("raw_mutton_slice", new Item(new Item.Properties()));
        helper.register("raw_pork_ribs", new Item(new Item.Properties()));
        helper.register("raw_pork_steak", new Item(new Item.Properties()));
        helper.register("raw_potato_fries", new Item(new Item.Properties()));
        helper.register("raw_rabbit_leg", new Item(new Item.Properties()));
        helper.register("raw_rabbit_slice", new Item(new Item.Properties()));
        helper.register("raw_salmon_fillet", new Item(new Item.Properties()));
        helper.register("rice", new Item(new Item.Properties()));
        helper.register("sake", new Item(new Item.Properties()));
        helper.register("salt", new Item(new Item.Properties()));
        helper.register("shredded_apple", new Item(new Item.Properties()));
        helper.register("shredded_cabbage", new Item(new Item.Properties()));
        helper.register("shredded_carrot", new Item(new Item.Properties()));
        helper.register("shredded_cucumber", new Item(new Item.Properties()));
        helper.register("shredded_ginger", new Item(new Item.Properties()));
        helper.register("shredded_lettuce", new Item(new Item.Properties()));
        helper.register("shredded_pear", new Item(new Item.Properties()));
        helper.register("shredded_potato", new Item(new Item.Properties()));
        helper.register("soybeans", new Item(new Item.Properties()));
        helper.register("soy_milk", new Item(new Item.Properties()));
        helper.register("soy_sauce", new Item(new Item.Properties()));
        helper.register("strawberry_extract", new Item(new Item.Properties()));
        helper.register("strawberry_marmalade", new Item(new Item.Properties()));
        helper.register("strawberry_slice", new Item(new Item.Properties()));
        helper.register("sweet_berry_extract", new Item(new Item.Properties()));
        helper.register("sweet_chilli_sauce", new Item(new Item.Properties()));
        helper.register("tomato_extract", new Item(new Item.Properties()));
        helper.register("tomato_slice", new Item(new Item.Properties()));
        helper.register("turmeric_powder", new Item(new Item.Properties()));
        helper.register("turmeric_slice", new Item(new Item.Properties()));
        helper.register("vanilla_powder", new Item(new Item.Properties()));
        helper.register("vinegar", new Item(new Item.Properties()));
        helper.register("walnuts", new Item(new Item.Properties()));
        helper.register("wine", new Item(new Item.Properties()));
        helper.register("apple_juice", new Item(new Item.Properties()));
        helper.register("apple_yogurt", new Item(new Item.Properties()));
        helper.register("banana_milkshake", new ConsumableItem(new Item.Properties().food(FoodList.CORN_MEAL), DrinkList.CORN_MEAL, UseAnim.DRINK));
        helper.register("blueberry_juice", new Item(new Item.Properties()));
        helper.register("blueberry_milkshake", new Item(new Item.Properties()));
        helper.register("blueberry_yogurt", new Item(new Item.Properties()));
        helper.register("carrot_juice", new Item(new Item.Properties()));
        helper.register("cherry_juice", new Item(new Item.Properties()));
        helper.register("cherry_yogurt", new Item(new Item.Properties()));
        helper.register("chocolate_milkshake", new Item(new Item.Properties()));
        helper.register("coconut_milkshake", new Item(new Item.Properties()));
        helper.register("coconut_yogurt", new Item(new Item.Properties()));
        helper.register("corn_dough", new Item(new Item.Properties()));
        helper.register("dough", new Item(new Item.Properties()));
        helper.register("empty_glass", new Item(new Item.Properties()));
        helper.register("empty_large_glass", new Item(new Item.Properties()));
        helper.register("grape_juice", new Item(new Item.Properties()));
        helper.register("grape_yogurt", new Item(new Item.Properties()));
        helper.register("hazelnut_yogurt", new Item(new Item.Properties()));
        helper.register("lemonade", new Item(new Item.Properties()));
        helper.register("lime_juice", new Item(new Item.Properties()));
        helper.register("melon_juice", new Item(new Item.Properties()));
        helper.register("nuts_milkshake", new Item(new Item.Properties()));
        helper.register("orange_juice", new Item(new Item.Properties()));
        helper.register("orange_yogurt", new Item(new Item.Properties()));
        helper.register("pasta_dough", new Item(new Item.Properties()));
        helper.register("peach_juice", new Item(new Item.Properties()));
        helper.register("peach_yogurt", new Item(new Item.Properties()));
        helper.register("pear_juice", new Item(new Item.Properties()));
        helper.register("pear_yogurt", new Item(new Item.Properties()));
        helper.register("pineapple_juice", new Item(new Item.Properties()));
        helper.register("pineapple_milkshake", new Item(new Item.Properties()));
        helper.register("pineapple_yogurt", new Item(new Item.Properties()));
        helper.register("plain_yogurt", new Item(new Item.Properties()));
        helper.register("plum_juice", new Item(new Item.Properties()));
        helper.register("plum_yogurt", new Item(new Item.Properties()));
        helper.register("potato_dough", new Item(new Item.Properties()));
        helper.register("raspberry_juice", new Item(new Item.Properties()));
        helper.register("raspberry_milkshake", new Item(new Item.Properties()));
        helper.register("raspberry_yogurt", new Item(new Item.Properties()));
        helper.register("raw_gnocchi", new Item(new Item.Properties()));
        helper.register("raw_lasagne_pasta", new Item(new Item.Properties()));
        helper.register("raw_noodles_pasta", new Item(new Item.Properties()));
        helper.register("raw_penne_pasta", new Item(new Item.Properties()));
        helper.register("raw_spaghetti_pasta", new Item(new Item.Properties()));
        helper.register("raw_tortellini_pasta", new Item(new Item.Properties()));
        helper.register("strawberry_juice", new Item(new Item.Properties()));
        helper.register("strawberry_milkshake", new Item(new Item.Properties()));
        helper.register("strawberry_yogurt", new Item(new Item.Properties()));
        helper.register("sweet_dough", new Item(new Item.Properties()));
        helper.register("tomato_juice", new Item(new Item.Properties()));
        helper.register("veggie_juice", new Item(new Item.Properties()));
        helper.register("backed_rabbit_leg", new Item(new Item.Properties()));
        helper.register("baked_potato_cuts", new Item(new Item.Properties()));
        helper.register("boiled_broccoli_cuts", new Item(new Item.Properties()));
        helper.register("boiled_cabbage_leaf", new Item(new Item.Properties()));
        helper.register("boiled_carrot_slice", new Item(new Item.Properties()));
        helper.register("boiled_corn_cob", new Item(new Item.Properties()));
        helper.register("boiled_gnocchi", new Item(new Item.Properties()));
        helper.register("boiled_lasagne_pasta", new Item(new Item.Properties()));
        helper.register("boiled_leek_slice", new Item(new Item.Properties()));
        helper.register("boiled_noodles_pasta", new Item(new Item.Properties()));
        helper.register("boiled_parsley_slice", new Item(new Item.Properties()));
        helper.register("boiled_peas", new Item(new Item.Properties()));
        helper.register("boiled_penne_pasta", new Item(new Item.Properties()));
        helper.register("boiled_potato_cuts", new Item(new Item.Properties()));
        helper.register("boiled_spaghetti_pasta", new Item(new Item.Properties()));
        helper.register("boiled_tortellini_pasta", new Item(new Item.Properties()));
        helper.register("burnt_bacon", new Item(new Item.Properties()));
        helper.register("burnt_beef_slice", new Item(new Item.Properties()));
        helper.register("burnt_beef_steak", new Item(new Item.Properties()));
        helper.register("burnt_beetroot_slice", new Item(new Item.Properties()));
        helper.register("burnt_bell_pepper_slice", new Item(new Item.Properties()));
        helper.register("burnt_broccoli_cuts", new Item(new Item.Properties()));
        helper.register("burnt_cabbage_leaf", new Item(new Item.Properties()));
        helper.register("burnt_chicken_breast", new Item(new Item.Properties()));
        helper.register("burnt_chicken_drumstick", new Item(new Item.Properties()));
        helper.register("burnt_chicken_wing", new Item(new Item.Properties()));
        helper.register("burnt_coffee_beans", new Item(new Item.Properties()));
        helper.register("burnt_corn_cob", new Item(new Item.Properties()));
        helper.register("burnt_diced_beef_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_beetroot", new Item(new Item.Properties()));
        helper.register("burnt_diced_carrot", new Item(new Item.Properties()));
        helper.register("burnt_diced_chicken_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_pork_meat", new Item(new Item.Properties()));
        helper.register("burnt_diced_scallion", new Item(new Item.Properties()));
        helper.register("burnt_diced_tomato", new Item(new Item.Properties()));
        helper.register("burnt_eggplant_slice", new Item(new Item.Properties()));
        helper.register("burnt_fish_fillet", new Item(new Item.Properties()));
        helper.register("burnt_fried_egg", new Item(new Item.Properties()));
        helper.register("burnt_fries", new Item(new Item.Properties()));
        helper.register("burnt_garlic_slice", new Item(new Item.Properties()));
        helper.register("burnt_gnocchi", new Item(new Item.Properties()));
        helper.register("burnt_lasagne_pasta", new Item(new Item.Properties()));
        helper.register("burnt_leek_slice", new Item(new Item.Properties()));
        helper.register("burnt_mutton_ribs", new Item(new Item.Properties()));
        helper.register("burnt_mutton_slice", new Item(new Item.Properties()));
        helper.register("burnt_noodles_pasta", new Item(new Item.Properties()));
        helper.register("burnt_parsley_slice", new Item(new Item.Properties()));
        helper.register("burnt_peanuts", new Item(new Item.Properties()));
        helper.register("burnt_peas", new Item(new Item.Properties()));
        helper.register("burnt_penne_pasta", new Item(new Item.Properties()));
        helper.register("burnt_pineapple_rings", new Item(new Item.Properties()));
        helper.register("burnt_pork_ribs", new Item(new Item.Properties()));
        helper.register("burnt_pork_steak", new Item(new Item.Properties()));
        helper.register("burnt_portobello_slice", new Item(new Item.Properties()));
        helper.register("burnt_potato_cuts", new Item(new Item.Properties()));
        helper.register("burnt_potato_slice", new Item(new Item.Properties()));
        helper.register("burnt_rabbit_leg", new Item(new Item.Properties()));
        helper.register("burnt_rabbit_slice", new Item(new Item.Properties()));
        helper.register("burnt_salmon_fillet", new Item(new Item.Properties()));
        helper.register("burnt_slice", new Item(new Item.Properties()));
        helper.register("burnt_spaghetti_pasta", new Item(new Item.Properties()));
        helper.register("burnt_toast", new Item(new Item.Properties()));
        helper.register("burnt_tortellini_pasta", new Item(new Item.Properties()));
        helper.register("chocolate_yogurt", new Item(new Item.Properties()));
        helper.register("cooked_bacon", new Item(new Item.Properties()));
        helper.register("cooked_beef_slice", new Item(new Item.Properties()));
        helper.register("cooked_beetroot_slice", new Item(new Item.Properties()));
        helper.register("cooked_bell_pepper_slice", new Item(new Item.Properties()));
        helper.register("cooked_chicken_breast", new Item(new Item.Properties()));
        helper.register("cooked_chicken_drumstick", new Item(new Item.Properties()));
        helper.register("cooked_diced_beef_meat", new Item(new Item.Properties()));
        helper.register("cooked_diced_beetroot", new Item(new Item.Properties()));
        helper.register("cooked_diced_carrot", new Item(new Item.Properties()));
        helper.register("cooked_diced_chicken_meat", new Item(new Item.Properties()));
        helper.register("cooked_diced_pork_meat", new Item(new Item.Properties()));
        helper.register("cooked_diced_scallion", new Item(new Item.Properties()));
        helper.register("cooked_diced_tomato", new Item(new Item.Properties()));
        helper.register("cooked_fish_fillet", new Item(new Item.Properties()));
        helper.register("cooked_fries", new Item(new Item.Properties()));
        helper.register("cooked_garlic_slice", new Item(new Item.Properties()));
        helper.register("cooked_leek_slice", new Item(new Item.Properties()));
        helper.register("cooked_portobello_slice", new Item(new Item.Properties()));
        helper.register("cooked_rabbit_slice", new Item(new Item.Properties()));
        helper.register("cooked_salmon_fillet", new Item(new Item.Properties()));
        helper.register("fried_potato_slice", new Item(new Item.Properties()));
        helper.register("grilled_beef_steak", new Item(new Item.Properties()));
        helper.register("grilled_carrot_slice", new Item(new Item.Properties()));
        helper.register("grilled_chicken_breast", new Item(new Item.Properties()));
        helper.register("grilled_chicken_drumstick", new Item(new Item.Properties()));
        helper.register("grilled_chicken_wing", new Item(new Item.Properties()));
        helper.register("grilled_corn_cob", new Item(new Item.Properties()));
        helper.register("grilled_eggplant_slice", new Item(new Item.Properties()));
        helper.register("grilled_fish_fillet", new Item(new Item.Properties()));
        helper.register("grilled_mutton_ribs", new Item(new Item.Properties()));
        helper.register("grilled_mutton_slice", new Item(new Item.Properties()));
        helper.register("grilled_pineapple_rings", new Item(new Item.Properties()));
        helper.register("grilled_pork_ribs", new Item(new Item.Properties()));
        helper.register("grilled_pork_steak", new Item(new Item.Properties()));
        helper.register("grilled_salmon_fillet", new Item(new Item.Properties()));
        helper.register("grilled_tomato_slice", new Item(new Item.Properties()));
        helper.register("roasted_coffee_beans", new Item(new Item.Properties()));
        helper.register("roasted_peanuts", new Item(new Item.Properties()));
        helper.register("toast", new Item(new Item.Properties()));
        helper.register("vanilla_milkshake", new Item(new Item.Properties()));
        helper.register("vanilla_yogurt", new Item(new Item.Properties()));
        helper.register("yeast", new Item(new Item.Properties()));
        helper.register("beef_jerky", new Item(new Item.Properties()));
        helper.register("boiled_tomato", new Item(new Item.Properties()));
        helper.register("bread_crumbs", new Item(new Item.Properties()));
        helper.register("burnt_camembert", new Item(new Item.Properties()));
        helper.register("burnt_tomato", new Item(new Item.Properties()));
        helper.register("butter", new Item(new Item.Properties()));
        helper.register("camembert", new Item(new Item.Properties()));
        helper.register("camembert_slice", new Item(new Item.Properties()));
        helper.register("cheese", new Item(new Item.Properties()));
        helper.register("cheese_cuts", new Item(new Item.Properties()));
        helper.register("cheese_slice", new Item(new Item.Properties()));
        helper.register("chicken_jerky", new Item(new Item.Properties()));
        helper.register("cream", new Item(new Item.Properties()));
        helper.register("cured_beef_steak", new Item(new Item.Properties()));
        helper.register("cured_chicken_breast", new Item(new Item.Properties()));
        helper.register("cured_pork_steak", new Item(new Item.Properties()));
        helper.register("grilled_camembert", new Item(new Item.Properties()));
        helper.register("milk", new Item(new Item.Properties()));
        helper.register("pork_jerky", new Item(new Item.Properties()));
        helper.register("rice_dough", new Item(new Item.Properties()));
        helper.register("shredded_cheese", new Item(new Item.Properties()));
        helper.register("shredded_garlic", new Item(new Item.Properties()));
        helper.register("sweet_rice_dough", new Item(new Item.Properties()));
        helper.register("tomato_sauce", new Item(new Item.Properties()));
        helper.register("whipped_cream", new Item(new Item.Properties()));
        helper.register("baguette", new Item(new Item.Properties()));
        helper.register("blueberry_ice_cream", new Item(new Item.Properties()));
        helper.register("burger_bun", new Item(new Item.Properties()));
        helper.register("burnt_baguette", new Item(new Item.Properties()));
        helper.register("burnt_bread", new Item(new Item.Properties()));
        helper.register("burnt_burger_bun", new Item(new Item.Properties()));
        helper.register("burnt_caramel", new Item(new Item.Properties()));
        helper.register("burnt_chocolate_bar", new Item(new Item.Properties()));
        helper.register("burnt_roll", new Item(new Item.Properties()));
        helper.register("burnt_waffle", new Item(new Item.Properties()));
        helper.register("caramel", new Item(new Item.Properties()));
        helper.register("caramel_ice_cream", new Item(new Item.Properties()));
        helper.register("cherry_ice_cream", new Item(new Item.Properties()));
        helper.register("chocolate_bar", new Item(new Item.Properties()));
        helper.register("chocolate_chips", new Item(new Item.Properties()));
        helper.register("chocolate_ice_cream", new Item(new Item.Properties()));
        helper.register("dried_baguette", new Item(new Item.Properties()));
        helper.register("dried_roll", new Item(new Item.Properties()));
        helper.register("grated_chocolate", new Item(new Item.Properties()));
        helper.register("ice_cream", new Item(new Item.Properties()));
        helper.register("lemon_ice_cream", new Item(new Item.Properties()));
        helper.register("raspberry_ice_cream", new Item(new Item.Properties()));
        helper.register("raw_baguette", new Item(new Item.Properties()));
        helper.register("raw_bread", new Item(new Item.Properties()));
        helper.register("raw_burger_bun", new Item(new Item.Properties()));
        helper.register("raw_roll", new Item(new Item.Properties()));
        helper.register("raw_waffle", new Item(new Item.Properties()));
        helper.register("roll", new Item(new Item.Properties()));
        helper.register("stracciatella_ice_cream", new Item(new Item.Properties()));
        helper.register("strawberry_ice_cream", new Item(new Item.Properties()));
        helper.register("vanilla_ice_cream", new Item(new Item.Properties()));
        helper.register("waffle", new Item(new Item.Properties()));
        helper.register("berry_tea", new Item(new Item.Properties()));
        helper.register("black_coffee", new Item(new Item.Properties()));
        helper.register("boiled_egg", new Item(new Item.Properties()));
        helper.register("boiled_egg_cuts", new Item(new Item.Properties()));
        helper.register("burnt_corn_bread", new Item(new Item.Properties()));
        helper.register("burnt_egg", new Item(new Item.Properties()));
        helper.register("burnt_nachos", new Item(new Item.Properties()));
        helper.register("burnt_pita", new Item(new Item.Properties()));
        helper.register("burnt_tortilla", new Item(new Item.Properties()));
        helper.register("cappuccino", new Item(new Item.Properties()));
        helper.register("citrus_tea", new Item(new Item.Properties()));
        helper.register("corn_bread", new Item(new Item.Properties()));
        helper.register("dandelion_tea", new Item(new Item.Properties()));
        helper.register("egg", new Item(new Item.Properties()));
        helper.register("espresso", new Item(new Item.Properties()));
        helper.register("fruit_tea", new Item(new Item.Properties()));
        helper.register("ginger_tea", new Item(new Item.Properties()));
        helper.register("honey_tea", new Item(new Item.Properties()));
        helper.register("hot_caramel_chocolate", new Item(new Item.Properties()));
        helper.register("hot_chilli_chocolate", new Item(new Item.Properties()));
        helper.register("hot_chocolate", new Item(new Item.Properties()));
        helper.register("ice_coffee", new Item(new Item.Properties()));
        helper.register("latte", new Item(new Item.Properties()));
        helper.register("milk_tea", new Item(new Item.Properties()));
        helper.register("mug", new Item(new Item.Properties()));
        helper.register("mulled_wine", new Item(new Item.Properties()));
        helper.register("nachos", new Item(new Item.Properties()));
        helper.register("pita", new Item(new Item.Properties()));
        helper.register("raw_corn_bread", new Item(new Item.Properties()));
        helper.register("raw_nachos", new Item(new Item.Properties()));
        helper.register("raw_pita", new Item(new Item.Properties()));
        helper.register("raw_tortilla", new Item(new Item.Properties()));
        helper.register("tea", new Item(new Item.Properties()));
        helper.register("tortilla", new Item(new Item.Properties()));
        helper.register("unfinished_mug", new Item(new Item.Properties()));
        helper.register("avocado_pesto", new Item(new Item.Properties()));
        helper.register("boiled_beans", new Item(new Item.Properties()));
        helper.register("bottle_of_water", new Item(new Item.Properties()));
        helper.register("burnt_beans", new Item(new Item.Properties()));
        helper.register("burnt_onion", new Item(new Item.Properties()));
        helper.register("burnt_soy_meat", new Item(new Item.Properties()));
        helper.register("burnt_spinach", new Item(new Item.Properties()));
        helper.register("cooked_onion", new Item(new Item.Properties()));
        helper.register("cooked_soy_meat", new Item(new Item.Properties()));
        helper.register("ice_tea", new Item(new Item.Properties()));
        helper.register("pesto", new Item(new Item.Properties()));
        helper.register("raw_soy_meat", new Item(new Item.Properties()));
        helper.register("rice_dumpling_wrapper", new Item(new Item.Properties()));
        helper.register("rice_paper", new Item(new Item.Properties()));
        helper.register("rock_salt", new Item(new Item.Properties()));
        helper.register("soy_flour", new Item(new Item.Properties()));
        helper.register("spinach", new Item(new Item.Properties()));
        helper.register("tofu", new Item(new Item.Properties()));
        helper.register("wheat_flour", new Item(new Item.Properties()));
    }
}
