name: "Release mod"
on:
  workflow_dispatch:
  push:
    tags:
      - 'version/*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Release
        run: ./gradlew releaseMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs:
      release

    steps:
      - name: Read changelog
        id: read_changelog
        run: |
          {
            echo "changelog_snippet<<EOF"
            head -n 11 ./CHANGELOG.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Trigger webhook
        env:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          SNIPPET: ${{ steps.read_changelog.outputs.changelog_snippet }}
        run: |
          jq -n \
          --arg snippet "$SNIPPET" \
            '{
              username: "Release bot",
              avatar_url: "https://cdn.discordapp.com/avatars/1308464796831711244/e886df028da3a37ad84b05e3fb0c3b8b.webp?size=32",
              content: "<@&1384152798232580197>",
              embeds: [
                {
                  title: "BlockyChef",
                  url: "https://github.com/T-T-Team/BlockyChef",
                  description: ($snippet),
                  color: 16179907,
                  thumbnail: { url: "https://media.forgecdn.net/avatars/1303/786/638847625782417518.png" },
                  fields: [
                    {
                      name: "CurseForge",
                      value: "[Download](<https://www.curseforge.com/minecraft/mc-mods/blockychef>)",
                      inline: true
                    },
                    {
                      name: "Sources",
                      value: "[GitHub](<https://github.com/T-T-Team/BlockyChef>)",
                      inline: true
                    },
                    {
                      name: "Support",
                      value: "[Patreon](<https://www.patreon.com/c/tnt_team>)",
                      inline: false
                    },
                    {
                      name: "Report issue",
                      value: "[GitHub](<https://github.com/T-T-Team/BlockyChef/issues>)",
                      inline: false
                    }
                  ],
                  footer: { text: "CurseForge file may take up to 1 hour to be published" }
                }
              ]
            }' > payload.json

          curl "$WEBHOOK" \
            -H "Content-Type: application/json" \
            --data @payload.json
